// SPDX-License-Identifier: Apache-2.0
//
// Every shipped example must run, and must produce what its own README says it
// produces.
//
// This is the test that stops the examples rotting. An example that no longer
// runs is worse than no example: it is the first thing a new reader tries, and
// its failure is the first thing they learn about the project.

#include "galata/analyze/gramians.hpp"
#include "galata/model/quadrotor.hpp"
#include "galata/pipeline/artifacts.hpp"
#include "galata/pipeline/pipeline.hpp"
#include "galata/pipeline/registry.hpp"

#include "integration_config.hpp"
#include <gtest/gtest.h>

#include <algorithm>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>

namespace {

std::string read_file(const std::filesystem::path& path) {
  std::ifstream file(path);
  std::ostringstream buffer;
  buffer << file.rdbuf();
  return buffer.str();
}

// Runs an example into a scratch directory, so a test never writes into the
// source tree.
galata::pipeline::RunResult run_example(const std::string& example, const std::string& study) {
  const std::filesystem::path directory = std::filesystem::path(GALATA_EXAMPLES_DIR) / example;
  const std::filesystem::path output =
      std::filesystem::path(GALATA_INTEGRATION_SCRATCH_DIR) / example;
  std::filesystem::create_directories(output);

  const galata::pipeline::Pipeline pipeline =
      galata::pipeline::load_pipeline((directory / study).string());
  return galata::pipeline::run_pipeline(pipeline,
                                        galata::pipeline::builtin_registry(),
                                        directory.string(),
                                        output.string(),
                                        nullptr,
                                        galata::pipeline::RunOptions{.overwrite = true});
}

TEST(ExampleNt33aLateralModes, RunsEndToEnd) {
  const auto result = run_example("nt33a-lateral-modes", "modal-study.yaml");
  ASSERT_EQ(result.stages.size(), 3U);
  EXPECT_EQ(result.stages[0].capability, "model.linear.statespace");
  EXPECT_EQ(result.stages[1].capability, "analyze.modes");
  EXPECT_EQ(result.stages[2].capability, "report.markdown");

  // Charter rule 9: every artefact carries the build that made it.
  for (const auto& stage : result.stages) {
    EXPECT_FALSE(stage.artifact.produced_by_capability.empty());
    EXPECT_NE(stage.artifact.produced_by_build.find("galata "), std::string::npos);
  }
}

TEST(ExampleNt33aLateralModes, ProducesTheModesItsReadmeClaims) {
  // The example's README quotes these numbers. If the model file or the
  // analysis changes, this fails and the README gets corrected — which is the
  // only way a README stays true.
  const auto result = run_example("nt33a-lateral-modes", "modal-study.yaml");
  const galata::pipeline::Artifact* report = result.find("report");
  ASSERT_NE(report, nullptr);

  const std::string path = std::any_cast<const std::string&>(report->payload);
  ASSERT_TRUE(std::filesystem::exists(path)) << path;
  const std::string text = read_file(path);

  // All three lateral modes are found and labelled.
  EXPECT_NE(text.find("spiral"), std::string::npos);
  EXPECT_NE(text.find("roll subsidence"), std::string::npos);
  EXPECT_NE(text.find("Dutch roll"), std::string::npos);

  // The report names its source, so a number cannot be quoted without it.
  EXPECT_NE(text.find("NASA CR-2144"), std::string::npos);
  EXPECT_NE(text.find("Generated by"), std::string::npos);

  // Participation factors are reported, and the table explains itself.
  EXPECT_NE(text.find("Participation factors"), std::string::npos);
  EXPECT_NE(text.find("condition number"), std::string::npos);
}

TEST(ExampleNt33aLateralModes, ModalValuesMatchThePublishedOnes) {
  // The same comparison the validation suite makes, repeated here against the
  // EXAMPLE's own model file rather than against the reference data. That is
  // the point: it checks that the numbers a user actually runs are the numbers
  // that were validated, and would catch a typo in the example's A matrix.
  const auto result = run_example("nt33a-lateral-modes", "modal-study.yaml");
  const galata::pipeline::Artifact* report = result.find("report");
  ASSERT_NE(report, nullptr);
  const std::string text = read_file(std::any_cast<const std::string&>(report->payload));

  // Published: spiral 1/T = 0.0318, roll subsidence 1/T = 2.20,
  // Dutch roll zeta = 0.0609, omega_n = 1.13 (NASA CR-2144 Table II-8).
  // The report prints four decimals, and the tolerance the validation suite
  // derives from the source's precision admits these exact strings.
  EXPECT_NE(text.find("-0.0319"), std::string::npos) << "spiral root not as published";
  EXPECT_NE(text.find("-2.1929"), std::string::npos) << "roll subsidence root not as published";
  EXPECT_NE(text.find("1.1297"), std::string::npos) << "Dutch roll omega_n not as published";
  EXPECT_NE(text.find("0.0607"), std::string::npos) << "Dutch roll zeta not as published";
}

TEST(ExampleNt33aBankLoopMargins, RunsEndToEnd) {
  const auto result = run_example("nt33a-bank-loop-margins", "margin-study.yaml");
  ASSERT_EQ(result.stages.size(), 5U);
  EXPECT_EQ(result.stages[0].capability, "model.linear.statespace");
  EXPECT_EQ(result.stages[1].capability, "analyze.freqresp");
  EXPECT_EQ(result.stages[2].capability, "analyze.margins");
  EXPECT_EQ(result.stages[3].capability, "analyze.diskmargin");
  EXPECT_EQ(result.stages[4].capability, "report.markdown");

  for (const auto& stage : result.stages) {
    EXPECT_FALSE(stage.artifact.produced_by_capability.empty());
    EXPECT_NE(stage.artifact.produced_by_build.find("galata "), std::string::npos);
  }
}

TEST(ExampleNt33aBankLoopMargins, ReportsTheThreeCrossoversItsReadmeQuotes) {
  // The example's whole point is that this loop has THREE gain crossovers and
  // that reporting only the first would call it comfortable. Its README prints
  // all three. If the model, the gain or the crossover search changes, this
  // fails and the README gets corrected.
  const auto result = run_example("nt33a-bank-loop-margins", "margin-study.yaml");
  const galata::pipeline::Artifact* report = result.find("report");
  ASSERT_NE(report, nullptr);
  const std::string text = read_file(std::any_cast<const std::string&>(report->payload));

  EXPECT_NE(text.find("All crossovers:"), std::string::npos);
  EXPECT_NE(text.find("0.59308"), std::string::npos) << "first gain crossover";
  EXPECT_NE(text.find("0.91805"), std::string::npos) << "second gain crossover";
  EXPECT_NE(text.find("1.61076"), std::string::npos) << "third, governing gain crossover";
  EXPECT_NE(text.find("101.015"), std::string::npos) << "phase margin at the first crossover";
  EXPECT_NE(text.find("48.486"), std::string::npos) << "the GOVERNING phase margin";

  // The governing margin is the smallest, not the first found.
  const std::size_t governing = text.find("| Phase | 48.486 deg |");
  EXPECT_NE(governing, std::string::npos)
      << "the headline phase margin must be the smallest of the three";

  // Infinite gain margin, which is exactly the case the disk margin exists to
  // qualify. The README says so; the report must too.
  EXPECT_NE(text.find("| Gain | not found in searched band |"), std::string::npos);
}

TEST(ExampleNt33aBankLoopMargins, DiskMarginQualifiesTheInfiniteGainMargin) {
  // The README claims an estimated gain range of roughly 0.39 to 2.56 and a
  // phase range of about +/- 47 degrees for a loop whose classical gain margin
  // is infinite. Those numbers are the example's whole argument, so they are
  // checked against the report a user actually reads.
  const auto result = run_example("nt33a-bank-loop-margins", "margin-study.yaml");
  const galata::pipeline::Artifact* report = result.find("report");
  ASSERT_NE(report, nullptr);
  const std::string text = read_file(std::any_cast<const std::string&>(report->payload));

  EXPECT_NE(text.find("| Disk margin alpha | 0.87548 |"), std::string::npos);
  EXPECT_NE(text.find("0.3911 to 2.5571"), std::string::npos)
      << "estimated gain range not as the README quotes it";
  EXPECT_NE(text.find("+/- 47.282 deg"), std::string::npos)
      << "estimated phase range not as the README quotes it";

  // The claim the example exists to make: a BOUNDED robustness margin sitting
  // underneath an INFINITE classical gain margin. If either half of that stops
  // being true, the example stops making its point and this fails.
  EXPECT_NE(text.find("| Gain | not found in searched band |"), std::string::npos);

  const auto* margins = result.find("margins");
  ASSERT_NE(margins, nullptr);
  EXPECT_NE(margins->summary.find("GM not found in searched band"), std::string::npos);
  EXPECT_EQ(margins->summary.find("GM infinite"), std::string::npos);

  // And the report must say how the peak was found, since a grid maximum makes
  // the disk margin an optimistic bound.
  EXPECT_NE(text.find("upper bound on the true disk margin"), std::string::npos);
}

TEST(ExampleNt33aLateralMimo, RunsEndToEnd) {
  const auto result = run_example("nt33a-lateral-mimo", "mimo-study.yaml");
  ASSERT_EQ(result.stages.size(), 5U);
  EXPECT_EQ(result.stages[0].capability, "model.linear.statespace");
  EXPECT_EQ(result.stages[1].capability, "analyze.sigma");
  EXPECT_EQ(result.stages[2].capability, "analyze.sensitivity");
  EXPECT_EQ(result.stages[3].capability, "analyze.margins");
  EXPECT_EQ(result.stages[4].capability, "report.markdown");
}

TEST(ExampleNt33aLateralMimo, ShowsThePerChannelMarginsBeingOptimistic) {
  // The example's argument, checked against the report a reader actually sees.
  // The aileron channel alone reports an INFINITE gain margin; the 2x2 loop has
  // M_S = 1.85. If either half stops being true the example stops making its
  // point, and its README stops being accurate.
  const auto result = run_example("nt33a-lateral-mimo", "mimo-study.yaml");
  const galata::pipeline::Artifact* report = result.find("report");
  ASSERT_NE(report, nullptr);
  const std::string text = read_file(std::any_cast<const std::string&>(report->payload));

  EXPECT_NE(text.find("| Sensitivity M_S | 1.84855 |"), std::string::npos);
  EXPECT_NE(text.find("| Complementary M_T | 1.80178 |"), std::string::npos);
  EXPECT_NE(text.find("| Gain | not found in searched band |"), std::string::npos);
  EXPECT_NE(text.find("48.486 deg"), std::string::npos);

  // The shortest distance to the critical point, which the README quotes.
  EXPECT_NE(text.find("0.54097"), std::string::npos);
  EXPECT_NE(text.find("smallest singular value of I+L"), std::string::npos);
}

TEST(ExampleNt33aLateralMimo, ReportsTwoPrincipalGainsAndTheirSpread) {
  const auto result = run_example("nt33a-lateral-mimo", "mimo-study.yaml");
  const galata::pipeline::Artifact* report = result.find("report");
  ASSERT_NE(report, nullptr);
  const std::string text = read_file(std::any_cast<const std::string&>(report->payload));

  EXPECT_NE(text.find("2 principal gains (2 outputs, 2 inputs)"), std::string::npos);
  // The condition number the README quotes as "about 96" at the low end.
  EXPECT_NE(text.find("| 0.01000 | 43.80798 | 0.45760 | 95.733 |"), std::string::npos)
      << "the low-frequency principal gains and their spread are what the README quotes";

  // And the guaranteed-margin bounds must be REFUSED here, with the reason,
  // rather than computed per channel.
  EXPECT_NE(text.find("stated for SINGLE-LOOP systems"), std::string::npos);
  EXPECT_EQ(text.find("gain margin at least"), std::string::npos)
      << "the SISO-only bounds must not appear for a 2x2 loop";
}

TEST(ExampleNt33aTrimAndLinearise, RunsTheWholeChainAndReproducesThePublishedModes) {
  // The example's README quotes these. If the model, the trim or the
  // linearisation changes, this fails and the README gets corrected — which is
  // the only mechanism that keeps a README true.
  const auto result = run_example("nt33a-trim-and-linearise", "study.yaml");
  ASSERT_EQ(result.stages.size(), 7U);
  EXPECT_EQ(result.stages[0].capability, "model.aircraft.derivatives");
  EXPECT_EQ(result.stages[1].capability, "trim.level");
  EXPECT_EQ(result.stages[2].capability, "linearize.finitediff");

  const galata::pipeline::Artifact* report = result.find("report");
  ASSERT_NE(report, nullptr);
  const std::string text = read_file(std::any_cast<const std::string&>(report->payload));

  // All five classical modes, found and labelled.
  for (const char* mode : {"phugoid", "short period", "spiral", "roll subsidence", "Dutch roll"}) {
    EXPECT_NE(text.find(mode), std::string::npos) << "missing mode: " << mode;
  }

  // The trim reports its own evidence rather than asserting itself.
  EXPECT_NE(text.find("Residual norm"), std::string::npos);
  EXPECT_NE(text.find("Jacobian condition number"), std::string::npos);
  EXPECT_NE(text.find("2.1481"), std::string::npos) << "trim alpha changed";

  // The numbers the README quotes.
  EXPECT_NE(text.find("0.0949"), std::string::npos) << "phugoid zeta changed";
  EXPECT_NE(text.find("0.6219"), std::string::npos) << "short period zeta changed";
  EXPECT_NE(text.find("0.0603"), std::string::npos) << "Dutch roll zeta changed";
  EXPECT_NE(text.find("-2.1992"), std::string::npos) << "roll subsidence root changed";

  // The state matrix is printed, so a reader can check it by hand.
  EXPECT_NE(text.find("State matrix A"), std::string::npos);
}

// ===========================================================================
// The quadrotor programme's two end-to-end examples
// ===========================================================================
//
// These run the SHIPPED study files, not a copy of them. An example that stops
// running is worse than no example, and these two are the only place the
// identification path and the sampled-control path are exercised through the
// public capabilities a user actually has.

TEST(ExampleQuadrotorSampledControl, RunsEndToEnd) {
  const auto result = run_example("quadrotor-sampled-control", "study.yaml");
  ASSERT_EQ(result.stages.size(), 12U);
  EXPECT_EQ(result.stages[0].capability, "model.quadrotor");
  EXPECT_EQ(result.stages[1].capability, "trim.hover");
  EXPECT_EQ(result.stages[2].capability, "linearize.extended");
  EXPECT_EQ(result.stages[3].capability, "model.channels");
  EXPECT_EQ(result.stages[4].capability, "synth.lqr");
  EXPECT_EQ(result.stages[5].capability, "analyze.gramians");
  EXPECT_EQ(result.stages[6].capability, "model.control_system");
  EXPECT_EQ(result.stages[7].capability, "analyze.margins");
  EXPECT_EQ(result.stages[8].capability, "analyze.diskmargin");
  EXPECT_EQ(result.stages[9].capability, "sim.sampled");
  for (const auto& stage : result.stages) {
    EXPECT_NE(stage.artifact.produced_by_build.find("galata "), std::string::npos);
  }
}

// The two analyses the audit found unavailable on this plant, exercised through
// the shipped study rather than through a test harness. What is asserted is
// that each is AVAILABLE and says what it does not establish; the values are
// properties of this study's declared weights and horizon and are not pinned.
TEST(ExampleQuadrotorSampledControl, ReportsWhatTheModelCanReachAndWhatTheLoopTolerates) {
  const auto result = run_example("quadrotor-sampled-control", "study.yaml");

  const galata::pipeline::Artifact* reach = result.find("reachability");
  ASSERT_NE(reach, nullptr);
  const auto& analysis = reach->payload_as<galata::analyze::GramianAnalysis>("gramians");
  EXPECT_EQ(analysis.reachability.rank, analysis.reachability.state_count);
  // The heading is unobservable from this sensor set, and the study reports it
  // by name before any design is trusted.
  EXPECT_LT(analysis.observability.rank, analysis.observability.state_count);
  EXPECT_FALSE(analysis.spectrum_is_strictly_stable)
      << "a hover linearisation has integrator eigenvalues, so no infinite-horizon Gramian "
         "exists and the report must not imply one was computed";

  const galata::pipeline::Artifact* margins = result.find("margins_0");
  ASSERT_NE(margins, nullptr);
  EXPECT_NE(margins->summary.find("PM "), std::string::npos) << margins->summary;
  const galata::pipeline::Artifact* disk = result.find("disk_0");
  ASSERT_NE(disk, nullptr);
  EXPECT_NE(disk->summary.find("alpha"), std::string::npos) << disk->summary;

  // And the report says, in the reader's path, that none of it is a statement
  // about the SAMPLED loop.
  const galata::pipeline::Artifact* report = result.find("report");
  ASSERT_NE(report, nullptr);
  const std::string text = read_file(std::any_cast<const std::string&>(report->payload));
  EXPECT_NE(text.find("sampled loop's own robustness"), std::string::npos)
      << "the report must not let a continuous-loop margin be read as a sampled-loop one";
}

// The point of the example: a law designed on the linearisation, executed at a
// declared rate against the NONLINEAR plant, removes the displacement it was
// started from. A budget rather than a tolerance — a metre of the two-metre
// initial offset would be a failure, and so would a run that diverged.
TEST(ExampleQuadrotorSampledControl, TheLawDrivesTheDisplacementOut) {
  const auto result = run_example("quadrotor-sampled-control", "study.yaml");
  const galata::pipeline::Artifact* closed = result.find("closed");
  ASSERT_NE(closed, nullptr);
  const auto& sampled = closed->payload_as<galata::pipeline::SampledRun>("sampled_trajectory");

  const Eigen::VectorXd& first = sampled.plant.trajectory.states.front();
  const Eigen::VectorXd& last = sampled.plant.trajectory.states.back();
  const galata::pipeline::Artifact* hover = result.find("hover");
  ASSERT_NE(hover, nullptr);
  const auto& trimmed = hover->payload_as<galata::pipeline::HoverTrimArtifact>("hover_trim");
  const Eigen::Vector3d reference = trimmed.point.extended_state.head<3>();

  const double started = (first.head<3>() - reference).norm();
  const double ended = (last.head<3>() - reference).norm();
  EXPECT_GT(started, 2.0) << "the study must actually displace the vehicle";
  EXPECT_LT(ended, 0.1 * started)
      << "the sampled law must remove at least nine tenths of the displacement it started "
         "from; started "
      << started << " m, ended " << ended << " m";
  EXPECT_EQ(sampled.control.delay_periods, 2);
}

TEST(ExampleQuadrotorIdentification, RunsEndToEnd) {
  const auto result = run_example("quadrotor-identification", "study.yaml");
  ASSERT_EQ(result.stages.size(), 12U);
  EXPECT_EQ(result.stages[1].capability, "data.import.csv");
  EXPECT_EQ(result.stages[2].capability, "data.window");
  EXPECT_EQ(result.stages[4].capability, "identify.greybox");
  EXPECT_EQ(result.stages[5].capability, "model.quadrotor.export");
  EXPECT_EQ(result.stages[6].capability, "trim.hover");
  EXPECT_EQ(result.stages[9].capability, "identify.validate");
}

// THE SELF-TEST. The example commits its own truth model, so this compares the
// recovered parameters against the file that generated the record rather than
// against a number typed here. A fit that converged to the wrong root passes a
// residual gate and fails this one.
TEST(ExampleQuadrotorIdentification, RecoversTheParametersItsTruthModelDeclares) {
  const auto result = run_example("quadrotor-identification", "study.yaml");
  const galata::pipeline::Artifact* fit = result.find("fit");
  ASSERT_NE(fit, nullptr);
  const auto& fitted = fit->payload_as<galata::pipeline::QuadrotorArtifact>("quadrotor");
  ASSERT_TRUE(fitted.identity.is_fitted());
  ASSERT_NE(fitted.identity.fit, nullptr);

  const galata::model::Quadrotor truth = galata::model::load_quadrotor(
      (std::filesystem::path(GALATA_EXAMPLES_DIR) / "quadrotor-identification" / "quad-truth.yaml")
          .string());

  // The record is the truth model's own output to round-off, so the budget is
  // set by the fit's own reported precision rather than by engineering
  // judgement: eight significant figures on each parameter.
  EXPECT_NEAR(fitted.model.mass.mass_kg, truth.mass.mass_kg, 1e-8 * truth.mass.mass_kg);
  EXPECT_NEAR(fitted.model.angular_drag_n_m_s(1),
              truth.angular_drag_n_m_s(1),
              1e-6 * truth.angular_drag_n_m_s(1));
  // And the base model it started from was genuinely wrong about both, so the
  // recovery is not an accident of the starting point.
  const galata::model::Quadrotor base = galata::model::load_quadrotor(
      (std::filesystem::path(GALATA_EXAMPLES_DIR) / "quadrotor-identification" / "quad-base.yaml")
          .string());
  EXPECT_GT(std::fabs(base.mass.mass_kg - truth.mass.mass_kg), 0.1);
  EXPECT_GT(std::fabs(base.angular_drag_n_m_s(1) - truth.angular_drag_n_m_s(1)), 1e-3);
}

// "Unfitted parameters are preserved" has to be a checked statement. This
// compares every parameter the study did not name against the BASE model, and
// requires the provenance to list each of them by name.
TEST(ExampleQuadrotorIdentification, PreservesEveryParameterItWasNotAskedToFit) {
  const auto result = run_example("quadrotor-identification", "study.yaml");
  const galata::pipeline::Artifact* fit = result.find("fit");
  ASSERT_NE(fit, nullptr);
  const auto& fitted = fit->payload_as<galata::pipeline::QuadrotorArtifact>("quadrotor");
  const galata::model::Quadrotor base = galata::model::load_quadrotor(
      (std::filesystem::path(GALATA_EXAMPLES_DIR) / "quadrotor-identification" / "quad-base.yaml")
          .string());

  ASSERT_EQ(fitted.model.rotor_count(), base.rotor_count());
  for (std::size_t r = 0; r < base.rotors.size(); ++r) {
    EXPECT_EQ(fitted.model.rotors[r].thrust_coefficient_n_s2,
              base.rotors[r].thrust_coefficient_n_s2)
        << "rotor " << r;
    EXPECT_EQ(fitted.model.rotors[r].torque_coefficient_n_m_s2,
              base.rotors[r].torque_coefficient_n_m_s2)
        << "rotor " << r;
    EXPECT_EQ(fitted.model.rotors[r].speed_time_constant_s, base.rotors[r].speed_time_constant_s)
        << "rotor " << r;
    EXPECT_EQ(fitted.model.rotors[r].position_cg_to_hub_body_m,
              base.rotors[r].position_cg_to_hub_body_m)
        << "rotor " << r;
  }
  EXPECT_EQ(fitted.model.drag_linear_n_s_m, base.drag_linear_n_s_m);
  EXPECT_EQ(fitted.model.drag_quadratic_n_s2_m2, base.drag_quadratic_n_s2_m2);
  EXPECT_EQ(fitted.model.angular_drag_n_m_s(0), base.angular_drag_n_m_s(0));
  EXPECT_EQ(fitted.model.angular_drag_n_m_s(2), base.angular_drag_n_m_s(2));
  EXPECT_EQ(fitted.model.mass.inertia_cg_body_kg_m2, base.mass.inertia_cg_body_kg_m2);

  // Twenty-two parameter paths exist on a four-rotor model; two were fitted.
  const auto& provenance = *fitted.identity.fit;
  EXPECT_EQ(provenance.fitted.size(), 2U);
  EXPECT_EQ(provenance.preserved_parameter_paths.size(), 20U);
  for (const auto& parameter : provenance.fitted) {
    EXPECT_FALSE(parameter.unit.empty()) << parameter.path << " has no unit";
    EXPECT_EQ(std::count(provenance.preserved_parameter_paths.begin(),
                         provenance.preserved_parameter_paths.end(),
                         parameter.path),
              0)
        << parameter.path << " is listed both as fitted and as preserved";
  }
}

// THE ONE THAT MATTERS FOR THE LABEL. Two stages of the same study run the same
// model against two windows of the same file. Their verdicts must differ, and
// neither may have been decided by comparing digests — the digests are equal in
// both cases, because both windows came from one import.
TEST(ExampleQuadrotorIdentification, LabelsTheHeldOutWindowAndTheTrainingWindowDifferently) {
  const auto result = run_example("quadrotor-identification", "study.yaml");
  const galata::pipeline::Artifact* held = result.find("check_heldout");
  const galata::pipeline::Artifact* trained = result.find("check_estimation");
  ASSERT_NE(held, nullptr);
  ASSERT_NE(trained, nullptr);

  const auto& held_out = held->payload_as<galata::pipeline::ValidationArtifact>("validation");
  const auto& on_training = trained->payload_as<galata::pipeline::ValidationArtifact>("validation");

  EXPECT_EQ(held_out.result.separation, galata::identify::RecordSeparation::VerifiedDisjoint);
  EXPECT_EQ(on_training.result.separation, galata::identify::RecordSeparation::NotHeldOut);
  // Both records came from one import, so the digests are EQUAL in both stages.
  // A classification that read the digests could not have separated them.
  EXPECT_EQ(held_out.result.estimation_record_sha256, held_out.result.validation_record_sha256);
  EXPECT_EQ(on_training.result.estimation_record_sha256,
            on_training.result.validation_record_sha256);
  EXPECT_FALSE(held_out.result.separation_basis.empty());
  EXPECT_NE(held_out.result.separation_basis, on_training.result.separation_basis);

  // The estimation digest was read from the fitted model's own provenance, not
  // declared in the study — study.yaml states no digest anywhere.
  const galata::pipeline::Artifact* fit = result.find("fit");
  ASSERT_NE(fit, nullptr);
  const auto& fitted = fit->payload_as<galata::pipeline::QuadrotorArtifact>("quadrotor");
  ASSERT_NE(fitted.identity.fit, nullptr);
  EXPECT_EQ(held_out.result.estimation_record_sha256,
            fitted.identity.fit->estimation_record_sha256);
}

TEST(ExampleNt33aLateralModes, EveryShippedExampleHasAReadme) {
  // A study nobody can read is a study nobody will run.
  for (const auto& entry :
       std::filesystem::directory_iterator(std::filesystem::path(GALATA_EXAMPLES_DIR))) {
    if (!entry.is_directory()) {
      continue;
    }
    EXPECT_TRUE(std::filesystem::exists(entry.path() / "README.md"))
        << entry.path().filename().string() << " has no README.md";
  }
}

}  // namespace
