// SPDX-License-Identifier: Apache-2.0
//
// Every shipped example must run, and must produce what its own README says it
// produces.
//
// This is the test that stops the examples rotting. An example that no longer
// runs is worse than no example: it is the first thing a new reader tries, and
// its failure is the first thing they learn about the project.

#include "galata/pipeline/pipeline.hpp"
#include "galata/pipeline/registry.hpp"

#include "integration_config.hpp"
#include <gtest/gtest.h>

#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>

namespace {

std::string read_file(const std::filesystem::path& path) {
  std::ifstream file(path);
  std::ostringstream buffer;
  buffer << file.rdbuf();
  return buffer.str();
}

// Runs an example into a scratch directory, so a test never writes into the
// source tree.
galata::pipeline::RunResult run_example(const std::string& example, const std::string& study) {
  const std::filesystem::path directory = std::filesystem::path(GALATA_EXAMPLES_DIR) / example;
  const std::filesystem::path output =
      std::filesystem::path(GALATA_INTEGRATION_SCRATCH_DIR) / example;
  std::filesystem::create_directories(output);

  const galata::pipeline::Pipeline pipeline =
      galata::pipeline::load_pipeline((directory / study).string());
  return galata::pipeline::run_pipeline(
      pipeline, galata::pipeline::builtin_registry(), directory.string(), output.string());
}

TEST(ExampleNt33aLateralModes, RunsEndToEnd) {
  const auto result = run_example("nt33a-lateral-modes", "modal-study.yaml");
  ASSERT_EQ(result.stages.size(), 3U);
  EXPECT_EQ(result.stages[0].capability, "model.linear.statespace");
  EXPECT_EQ(result.stages[1].capability, "analyze.modes");
  EXPECT_EQ(result.stages[2].capability, "report.markdown");

  // Charter rule 9: every artefact carries the build that made it.
  for (const auto& stage : result.stages) {
    EXPECT_FALSE(stage.artifact.produced_by_capability.empty());
    EXPECT_NE(stage.artifact.produced_by_build.find("galata "), std::string::npos);
  }
}

TEST(ExampleNt33aLateralModes, ProducesTheModesItsReadmeClaims) {
  // The example's README quotes these numbers. If the model file or the
  // analysis changes, this fails and the README gets corrected — which is the
  // only way a README stays true.
  const auto result = run_example("nt33a-lateral-modes", "modal-study.yaml");
  const galata::pipeline::Artifact* report = result.find("report");
  ASSERT_NE(report, nullptr);

  const std::string path = std::any_cast<const std::string&>(report->payload);
  ASSERT_TRUE(std::filesystem::exists(path)) << path;
  const std::string text = read_file(path);

  // All three lateral modes are found and labelled.
  EXPECT_NE(text.find("spiral"), std::string::npos);
  EXPECT_NE(text.find("roll subsidence"), std::string::npos);
  EXPECT_NE(text.find("Dutch roll"), std::string::npos);

  // The report names its source, so a number cannot be quoted without it.
  EXPECT_NE(text.find("NASA CR-2144"), std::string::npos);
  EXPECT_NE(text.find("Generated by"), std::string::npos);

  // Participation factors are reported, and the table explains itself.
  EXPECT_NE(text.find("Participation factors"), std::string::npos);
  EXPECT_NE(text.find("condition number"), std::string::npos);
}

TEST(ExampleNt33aLateralModes, ModalValuesMatchThePublishedOnes) {
  // The same comparison the validation suite makes, repeated here against the
  // EXAMPLE's own model file rather than against the reference data. That is
  // the point: it checks that the numbers a user actually runs are the numbers
  // that were validated, and would catch a typo in the example's A matrix.
  const auto result = run_example("nt33a-lateral-modes", "modal-study.yaml");
  const galata::pipeline::Artifact* report = result.find("report");
  ASSERT_NE(report, nullptr);
  const std::string text = read_file(std::any_cast<const std::string&>(report->payload));

  // Published: spiral 1/T = 0.0318, roll subsidence 1/T = 2.20,
  // Dutch roll zeta = 0.0609, omega_n = 1.13 (NASA CR-2144 Table II-8).
  // The report prints four decimals, and the tolerance the validation suite
  // derives from the source's precision admits these exact strings.
  EXPECT_NE(text.find("-0.0319"), std::string::npos) << "spiral root not as published";
  EXPECT_NE(text.find("-2.1929"), std::string::npos) << "roll subsidence root not as published";
  EXPECT_NE(text.find("1.1297"), std::string::npos) << "Dutch roll omega_n not as published";
  EXPECT_NE(text.find("0.0607"), std::string::npos) << "Dutch roll zeta not as published";
}

TEST(ExampleNt33aLateralModes, EveryShippedExampleHasAReadme) {
  // A study nobody can read is a study nobody will run.
  for (const auto& entry :
       std::filesystem::directory_iterator(std::filesystem::path(GALATA_EXAMPLES_DIR))) {
    if (!entry.is_directory()) {
      continue;
    }
    EXPECT_TRUE(std::filesystem::exists(entry.path() / "README.md"))
        << entry.path().filename().string() << " has no README.md";
  }
}

}  // namespace
