// SPDX-License-Identifier: Apache-2.0
//
// Loader for the reference-data files in reference/.
//
// Deliberately minimal and deliberately strict. It refuses a file with no
// citation header, because an uncited reference table is exactly the thing
// charter rule 8 exists to prevent: a number that looks authoritative and came
// from nowhere.

#ifndef GALATA_TOOLS_VALIDATION_REFERENCE_TABLE_HPP
#define GALATA_TOOLS_VALIDATION_REFERENCE_TABLE_HPP

#include <map>
#include <string>
#include <vector>

namespace galata::testing {

struct ReferenceTable {
  // Every '#' line at the top of the file, joined. Printed in a failure message
  // so that a failing validation names its source in the CI log.
  std::string citation;
  std::vector<std::string> columns;

  // Numeric view: only the fields that parse as a number appear here.
  std::vector<std::map<std::string, double>> rows;

  // Text view: every field, exactly as it appears in the file.
  //
  // Reference files come in two shapes. A wide table has one row per altitude
  // and one numeric column per quantity. A long table has one row per quantity,
  // with the quantity's NAME in one column and its value in another — which is
  // the only sane shape for a heterogeneous data set like an aircraft's
  // derivatives, where "wing area" and "C_m_alpha" have nothing in common but
  // the document they came from. Both are parsed by the same loader.
  std::vector<std::map<std::string, std::string>> text_rows;

  [[nodiscard]] double at(std::size_t row, const std::string& column) const;
  [[nodiscard]] const std::string& text(std::size_t row, const std::string& column) const;

  // For a long-format table: map `key_column` -> `value_column`, as numbers.
  //
  // Throws if a key repeats. A duplicated key in a transcribed reference file
  // means the transcription is wrong, and silently keeping the last one would
  // hide it.
  [[nodiscard]] std::map<std::string, double> as_lookup(const std::string& key_column,
                                                        const std::string& value_column) const;
};

// Loads <directory>/<name>. Throws if the file is missing, has no citation
// header, or has a row whose column count does not match the header.
//
// The directory is a parameter rather than a compiled-in path so that the
// validation test suite and the report generator read exactly the same files
// through the same parser. A report generated by a second, subtly different
// reader would be a report about a different set of numbers.
[[nodiscard]] ReferenceTable load_reference(const std::string& directory, const std::string& name);

// `units_in_last_place` units in the last printed significant figure of
// `printed`.
//
// 0.5 is exact agreement: the computed value rounds to the printed one.
// 1.0 allows the last printed digit to differ by one.
//
// The allowance is a parameter rather than a hidden constant because it is a
// published claim. docs/VERIFICATION.md records which cases need more than 0.5
// and by how much; a gate that silently absorbed that would be hiding the one
// number a reader of a validation report actually wants.
[[nodiscard]] double printed_precision_tolerance(double printed,
                                                 int significant_figures,
                                                 double units_in_last_place = 0.5);

}  // namespace galata::testing

#endif  // GALATA_TOOLS_VALIDATION_REFERENCE_TABLE_HPP
