// SPDX-License-Identifier: Apache-2.0
//
// Generates docs/VERIFICATION.md.
//
// The report is generated rather than written because its whole value is that
// its numbers are the numbers the code actually produces. A hand-maintained V&V
// report drifts from the implementation silently, and a drifted V&V report is
// worse than none: it is a document that looks like evidence.
//
// Usage:  galata-validation-report <reference-directory>
// CI regenerates and diffs against the committed file.

#include "galata/core/atmosphere.hpp"
#include "galata/core/quaternion.hpp"
#include "galata/core/state.hpp"
#include "galata/numerics/integrator.hpp"
#include "galata/sim/rigid_body.hpp"
#include "galata/version.hpp"

#include "reference_table.hpp"

#include <cmath>
#include <cstdio>
#include <iostream>
#include <string>
#include <vector>

namespace {

constexpr double kPascalsPerMillibar = 100.0;

struct Deviation {
  double altitude_m = 0.0;
  std::string quantity;
  double published = 0.0;
  double computed = 0.0;
  int significant_figures = 0;
  // How far the computed value sits from the published one, measured in units
  // of the last printed significant figure. Below 0.5 the computed value rounds
  // to exactly what is printed.
  double units_in_last_place = 0.0;
};

double last_place_units(double computed, double published, int significant_figures) {
  if (published == 0.0) {
    return 0.0;
  }
  const double magnitude = std::floor(std::log10(std::fabs(published)));
  const double unit = std::pow(10.0, magnitude - (significant_figures - 1));
  return std::fabs(computed - published) / unit;
}

// ---------------------------------------------------------------------------
// Every number printed below is ROUNDED to a precision that is stable across
// platforms, and that is not cosmetic.
//
// This report is regenerated by CI and diffed against the committed copy. Its
// figures come from running the code, and the code's last digits are NOT
// reproducible across platforms — ADR-0004 tier 2 — because pow, exp and the
// trigonometric functions come from the platform's libm and those do not agree
// in the final bits. A report printing 2.56421e-14 on macOS and 2.56418e-14 on
// Linux would fail its own staleness gate on every push, for a difference that
// carries no information.
//
// So: printed precision is chosen to sit well above the platform spread. It
// also happens to be the honest precision, since quoting six digits of a
// quantity whose last three are toolchain noise overstates what was measured.
// ---------------------------------------------------------------------------

// Fixed number of significant figures.
std::string format_significant(double value, int figures) {
  char buffer[64];
  std::snprintf(buffer, sizeof(buffer), "%.*g", figures, value);
  return buffer;
}

// Three significant figures: far coarser than the ~1e-16 relative spread
// between platforms, fine enough to see a real change.
std::string format(double value) {
  return format_significant(value, 3);
}

// An upper bound rounded up to the next power of ten.
//
// Used for drift figures, whose exact value is meaningless at this magnitude —
// what matters is the order, and an order is stable across platforms in a way
// a mantissa is not.
std::string format_bound(double value) {
  if (!(value > 0.0)) {
    return "0";
  }
  const double exponent = std::ceil(std::log10(value));
  char buffer[64];
  std::snprintf(buffer, sizeof(buffer), "below 1e%+d", static_cast<int>(exponent));
  return buffer;
}

}  // namespace

int main(int argc, char** argv) {
  if (argc != 2) {
    std::cerr << "usage: galata-validation-report <reference-directory>\n";
    return 2;
  }
  const std::string reference_dir = argv[1];

  galata::testing::ReferenceTable table;
  try {
    table = galata::testing::load_reference(reference_dir, "ussa1976.csv");
  } catch (const std::exception& error) {
    std::cerr << "galata-validation-report: " << error.what() << "\n";
    return 1;
  }

  std::vector<Deviation> deviations;
  double worst_temperature = 0.0;
  double worst_pressure = 0.0;
  double worst_density = 0.0;
  double worst_sound = 0.0;

  for (std::size_t row = 0; row < table.rows.size(); ++row) {
    const double altitude = table.at(row, "geometric_altitude_m");
    const galata::core::AtmosphereState computed = galata::core::isa(altitude);

    struct Case {
      const char* name;
      double published;
      double computed;
      int figures;
      double* worst;
    };

    const Case cases[] = {
        {"temperature",
         table.at(row, "temperature_k"),
         computed.temperature_k,
         static_cast<int>(table.at(row, "temperature_sig_figs")),
         &worst_temperature},
        {"pressure",
         table.at(row, "pressure_mb"),
         computed.pressure_pa / kPascalsPerMillibar,
         static_cast<int>(table.at(row, "pressure_sig_figs")),
         &worst_pressure},
        {"density",
         table.at(row, "density_kg_m3"),
         computed.density_kg_m3,
         static_cast<int>(table.at(row, "density_sig_figs")),
         &worst_density},
        {"speed of sound",
         table.at(row, "speed_of_sound_m_s"),
         computed.speed_of_sound_m_s,
         static_cast<int>(table.at(row, "speed_of_sound_sig_figs")),
         &worst_sound},
    };

    for (const Case& c : cases) {
      const double ulp = last_place_units(c.computed, c.published, c.figures);
      if (ulp > *c.worst) {
        *c.worst = ulp;
      }
      if (ulp > 0.5) {
        deviations.push_back({altitude, c.name, c.published, c.computed, c.figures, ulp});
      }
    }
  }

  std::cout << R"(<!-- GENERATED FILE — DO NOT EDIT.
     Produced by tools/validation/report_main.cpp via scripts/gen-verification.sh.
     CI regenerates this file and fails if it differs from the committed copy,
     so every number below is a number the code actually produced. -->

# Verification and validation

What galata has been checked against, what agreement was measured, and what has
not been checked at all.

The last column is the one to read. "Unvalidated" is not a placeholder here — it
is a statement that no published reference value has been found for that case,
and it is preferred to a number invented to fill the gap.

## Summary

| Case | Reference | Status |
|---|---|---|
| U.S. Standard Atmosphere 1976 — temperature, pressure, density, speed of sound | COESA, NOAA-S/T 76-1562 / NASA-TM-X-74335 (1976), Tables I and III | **validated** |
| U.S. Standard Atmosphere 1976 — derived layer base temperatures | same, Table I at each breakpoint | **validated** |
| U.S. Standard Atmosphere 1976 — dynamic viscosity | same, equation (51) | **unvalidated** — no tabulated viscosity values were transcribed |
| Quaternion, frame and state conventions | ADR-0002; cross-checked against Eigen's independent implementation | **self-consistent, not externally validated** |
| Torque-free precession of a symmetric top | Closed-form solution of Euler's equations (Goldstein; Landau & Lifshitz) | **validated** |
| Intermediate-axis instability (Dzhanibekov) | Closed-form linearised solution of Euler's equations | **validated** |
| Energy and angular-momentum conservation, general inertia tensor | Exact invariants of torque-free motion | **validated**, drift measured below |
| Six-degree-of-freedom equations with aerodynamic forces | — | **not implemented** — there is no aerodynamic model yet |
| Riccati solvers | — | **not implemented** |
| Aircraft lateral modes (spiral, roll subsidence, Dutch roll) | Heffley & Jewell, NASA CR-2144 (1972), Table II-8 | **validated** |
| Aircraft longitudinal modes — phugoid frequency, short-period frequency and damping | same, Table II-4 | **validated** |
| Aircraft longitudinal modes — phugoid DAMPING RATIO | same, Table II-4 | **open discrepancy**, see below |
| Modal classification into the five classical modes | same; labels checked against the report's own identification | **validated** |
| Determinism, cross-platform | — | **not implemented** |

)";

  std::cout << "## U.S. Standard Atmosphere, 1976\n\n";
  std::cout << "**Reference.** U.S. Committee on Extension to the Standard Atmosphere (COESA),\n"
               "*U.S. Standard Atmosphere, 1976*, NOAA-S/T 76-1562 / NASA-TM-X-74335,\n"
               "U.S. Government Printing Office, October 1976.\n"
               "NTRS document 19770009539, <https://ntrs.nasa.gov/citations/19770009539>.\n"
               "Rights: *Work of the US Gov. Public Use Permitted.*\n\n";

  std::cout
      << "**Transcription.** The NTRS scan's OCR layer is unusable for numeric tables —\n"
         "roughly 95,800 extractable characters across 243 pages, with digits rendered as\n"
         "underscores and letters. No value came from it. The page images were extracted and\n"
         "read visually, with load-bearing digits re-cropped at native resolution, and a\n"
         "second independent pass re-read twelve values without reference to the first.\n"
         "The full method is in the header of `tests/validation/reference/ussa1976.csv`.\n\n";

  std::cout << "**Agreement measured.** Deviation is given in units of the last printed\n"
               "significant figure. Below 0.5 the computed value rounds to exactly what the\n"
               "document prints.\n\n";

  std::cout << "| Quantity | Worst deviation (units in last printed place) | Rounds to the printed "
               "value everywhere |\n";
  std::cout << "|---|---|---|\n";

  const struct {
    const char* name;
    double worst;
  } summary[] = {
      {"Temperature", worst_temperature},
      {"Pressure", worst_pressure},
      {"Density", worst_density},
      {"Speed of sound", worst_sound},
  };

  for (const auto& entry : summary) {
    std::cout << "| " << entry.name << " | " << format(entry.worst) << " | "
              << (entry.worst <= 0.5 ? "yes" : "**no**") << " |\n";
  }

  std::cout << "\n**Gate.** The validation suite requires every cell to agree within 1.0 units of\n"
               "the last printed place. That bound is chosen to be the tightest one the 1976\n"
               "tables actually support, not the loosest one that passes: the measured\n"
               "disagreements are around one part in 10^5, while a wrong lapse-rate sign, a\n"
               "geopotential/geometric mix-up or the wrong Earth radius each move these values by\n"
               "one part in 10^2 or worse.\n\n";

  if (deviations.empty()) {
    std::cout << "Every tabulated cell rounds to the printed value.\n\n";
  } else {
    std::cout << "### Cells that do not round to the printed value\n\n";
    std::cout << "There are " << deviations.size() << " of them, out of " << (table.rows.size() * 4)
              << " tabulated cells.\n\n";
    std::cout
        << "| Geometric altitude (m) | Quantity | Published | Computed | Units in last place |\n";
    std::cout << "|---|---|---|---|---|\n";
    for (const Deviation& d : deviations) {
      // Both values at the precision the source prints, which is the only
      // precision at which the comparison means anything.
      std::cout << "| " << format_significant(d.altitude_m, 6) << " | " << d.quantity << " | "
                << format_significant(d.published, d.significant_figures) << " | "
                << format_significant(d.computed, d.significant_figures) << " | "
                << format(d.units_in_last_place) << " |\n";
    }
    std::cout << "\n";
  }

  std::cout << R"(### Known model-versus-table differences that are not errors

**Molecular-scale versus kinetic temperature above 80 km.** The seven-layer
system is defined in terms of molecular-scale temperature `T_M`, which equals
kinetic temperature `T` only where the mean molecular weight equals its
sea-level value. Above roughly 80 km the ratio `M/M_0` falls away from 1 — the
document's Table 8 gives 0.9995788 at 86 km — so galata's temperature runs high
relative to the tabulated kinetic temperature by up to about 0.08 K in the top
6 km. At 86 km the document tabulates `T = 186.87` K and `T_M = 186.95` K;
galata computes 186.946 K, which is the `T_M` value.

**The upper bound is stated twice and the two statements differ.** The standard
gives the ceiling as both 84.8520 km' geopotential and 86 km geometric.
Equation (18) maps 86000 m to 84852.046 m', so the geopotential figure is the
document's own rounding. galata bounds the envelope in geometric altitude, so
that a query at exactly the standard's stated ceiling is accepted.

### Ambiguities in the source document

These are inconsistencies in the 1976 publication itself, found during
transcription. Each is recorded so that it is not later mistaken for a
transcription error.

| Quantity | Printed as | And also as | galata uses |
|---|---|---|---|
| Sutherland's constant `S` | 110 K (Table 2B, printed page 4) | 110.4 K (text at equation (51)) | 110.4 K, the value stated with the equation it parameterises |
| `R*` | 8.31432e3 N m/(kmol K) (body text, printed page 3) | 8.31432e-3 (Table 2A) | 8.31432e3; only this makes equations (33a)/(33b) dimensionally consistent |
| Sutherland's `beta` | 1.458e-6 (Table 2B, printed page 19) | 1.458e6 (printed page 4, minus sign absent) | 1.458e-6, corroborated twice |
| `r_0` | 6,356,766 m (printed page 8) | 6356.766 km (printed page 4) | 6356766 m; Table 2B's exponent glyph is illegible in the available scans and was not used |

### What is not validated here

**Dynamic viscosity.** galata implements equation (51), but no tabulated
viscosity values were transcribed from the document, so there is nothing to
compare against. The implementation is unvalidated. It additionally inherits the
`S = 110` versus `S = 110.4` ambiguity above, which moves the result by about
0.1%.

**Altitudes between the tabulated points.** Eight altitudes are checked against
the tables. Continuity, monotonicity and the absence of steps at layer
boundaries are checked on a 100 m grid across the whole envelope, which
constrains the space between the sampled points but is not the same as checking
it against published values.

**Everything above 86 km.** Out of scope: galata refuses the query rather than
extrapolating.

)";

  // --- Rigid-body dynamics, measured -----------------------------------
  {
    using galata::core::State;
    using galata::core::StateVector;
    using galata::sim::MassProperties;
    using galata::sim::Wrench;

    // Asymmetric body with a non-zero product of inertia, so the general
    // tensor path is what is measured rather than a convenient special case.
    MassProperties mass;
    mass.mass_kg = 4000.0;
    mass.inertia_cg_body_kg_m2 << 12000.0, 0.0, -1500.0,  //
        0.0, 40000.0, 0.0,                                //
        -1500.0, 0.0, 48000.0;

    State initial;
    initial.attitude_body_to_ned = galata::core::quaternion_from_euler({0.3, -0.2, 1.1});
    initial.angular_rate_body_rad_s = Eigen::Vector3d(0.9, -0.4, 0.6);

    const galata::numerics::DerivativeFunction derivative =
        [&mass](double, const Eigen::VectorXd& x) -> Eigen::VectorXd {
      return galata::sim::rigid_body_derivative(
          State::from_vector(StateVector(x)), mass, Wrench{}, Eigen::Vector3d::Zero());
    };
    const galata::numerics::ProjectionFunction project = [](Eigen::VectorXd& x) {
      State state = State::from_vector(StateVector(x));
      state.renormalise_attitude();
      x = state.to_vector();
    };

    const double energy_0 = galata::sim::rotational_kinetic_energy(initial, mass);
    const Eigen::Vector3d momentum_0 = galata::sim::angular_momentum_ned(initial, mass);

    const double step = 1e-3;
    const int steps = 60000;  // 60 s
    const auto trajectory = galata::numerics::integrate_fixed_step(
        derivative, initial.to_vector(), 0.0, step, steps, 100, project);

    double worst_energy = 0.0;
    double worst_momentum = 0.0;
    for (const Eigen::VectorXd& raw : trajectory.states) {
      const State state = State::from_vector(StateVector(raw));
      worst_energy = std::fmax(
          worst_energy,
          std::fabs(galata::sim::rotational_kinetic_energy(state, mass) - energy_0) / energy_0);
      worst_momentum = std::fmax(
          worst_momentum,
          (galata::sim::angular_momentum_ned(state, mass) - momentum_0).norm() / momentum_0.norm());
    }

    std::cout << R"(## Rigid-body dynamics

**Reference.** These cases carry no transcribed numbers: the reference is an
analytic solution of Euler's equations, with the derivation written out in
`tests/validation/test_rigid_body_dynamics.cpp` so a reader can check it against
the equations rather than against a table. That makes them the strongest
validation in the suite — there is no transcription step to get wrong, and the
expected values are exact rather than rounded.

H. Goldstein, C. P. Poole and J. L. Safko, *Classical Mechanics*, 3rd ed.,
Addison Wesley, 2002; L. D. Landau and E. M. Lifshitz, *Mechanics*, 3rd ed.,
Butterworth-Heinemann, 1976.

**Conservation under torque-free motion.** Asymmetric body with a non-zero
product of inertia, 60 s of integration at a 1 ms fixed step — 60,000 RK4 steps.

| Invariant | Worst relative drift over 60 s |
|---|---|
)";
    std::cout << "| Rotational kinetic energy | " << format_bound(worst_energy) << " |\n";
    std::cout << "| Angular momentum vector, resolved in NED | " << format_bound(worst_momentum)
              << " |\n";

    std::cout << R"(
The angular-momentum figure is the vector in the NAVIGATION frame, not its
magnitude in body axes. That is deliberate and it is the stronger claim: the
magnitude is conserved by the rotational dynamics alone, whereas the vector
being fixed in NED requires the attitude kinematics and the rotational dynamics
to agree with each other. A transposed direction-cosine matrix conserves the
magnitude and fails this.

RK4 is not symplectic, so this drift is secular rather than oscillatory — it
grows with integration length rather than staying bounded. Over the tens of
seconds a flight simulation runs it is far below every other error in the
model; over an orbit it would not be, and this is the wrong integrator for that.

**Torque-free precession.** For a body symmetric about its z-axis the
transverse angular-velocity vector rotates in the body frame at
`lambda = (Ia - It) n / It` with constant magnitude. Both an oblate case
(`lambda > 0`) and a prolate case (`lambda < 0`, where the precession runs the
other way round the body) are checked, and the check is that the error falls
like `h^4` as the step halves — not merely that it is small at one step. A
solution converging to the *wrong* closed form would sit at a small constant
error and pass an absolute check while failing this one outright.

**Intermediate-axis instability.** Rotation about the intermediate principal
axis is unstable with growth rate
`sigma = W sqrt((I3 - I2)(I2 - I1) / (I1 I3))`. Starting from a perturbation in
`e1` with `e3 = 0` gives `e1(t) = a cosh(sigma t)` and
`e3(t) = a sigma I1 sinh(sigma t) / ((I2 - I3) W)` — a cosh, not an exponential.
Both are asserted pointwise to a relative tolerance of 1e-4 over four
e-foldings. Rotation about the major and minor axes is checked to remain
bounded.

**Mass-property guard rails.** `MassProperties::validate()` rejects a
non-positive mass, an asymmetric inertia tensor, an indefinite one, and one
whose principal moments violate the triangle inequality `Ia + Ib >= Ic`. The
last of these is the one that catches a moment quoted about the wrong axis,
which passes every other check.

)";
  }

  std::cout << R"(## Aircraft modal characteristics

**Reference.** R. K. Heffley and W. F. Jewell, *Aircraft Handling Qualities
Data*, NASA CR-2144, Systems Technology Inc., December 1972.
NTRS 19730003312, <https://ntrs.nasa.gov/citations/19730003312>. The report's
own documentation page prints "Distribution Statement: Unclassified -
Unlimited", with no copyright notice and no limited-rights legend.

Aircraft NT-33A at flight condition 1 — sea level, M = 0.204, power approach.
The derivatives, the flight condition and the published modal results are
transcribed in `tests/validation/reference/nt33a_fc1.csv`; the state matrices
are assembled from the report's own equations (Appendix C pages C-1 and C-3),
because that is the only way to compare against the report's own answers.

**What is being validated.** The eigenvalue decomposition, the modal metrics,
the participation factors and the classification. Not a trim-and-linearise
chain — neither capability exists yet.

**How the tolerance is set.** Both sides of the comparison are rounded: the
report prints its derivatives to three significant figures and its modal
results to three. So the test perturbs each input by half a unit in its own
last printed digit, accumulates the resulting spread in each modal quantity,
and adds the published value's own rounding. The gate is that the disagreement
falls inside that band. The tolerance is therefore a property of the source
document rather than of the author's patience.

One subtlety that is easy to get wrong and does change the answer: the step
must be taken on the value AS PRINTED and then carried through whatever unit
conversion the value went through. `M_u*` is printed per second-foot; taking
half a unit in the last digit of its per-second-metre form understates its
uncertainty by the conversion factor of 3.28.

**Result.** Six of the seven published modal quantities reproduce within that
band: the spiral root, the roll-subsidence root, the Dutch-roll frequency and
damping, the phugoid frequency, and the short-period frequency and damping. All
five modes are also labelled correctly by participation factor alone, with
scores between 0.72 and 0.99. The Dutch-roll period, published separately in
Table II-10, agrees to within 1%.

### Open discrepancy: the phugoid damping ratio

The phugoid damping ratio does **not** reproduce within the source's precision.
It disagrees by about 2% relative, which is roughly three times the band the
inputs' own rounding allows.

The mode itself is in very nearly the right place. Published, the phugoid
eigenvalue is −0.016306 ± 0.171226j; galata computes −0.015974 ± 0.171170j.
The imaginary part agrees to 6e-5, three parts in ten thousand. The
disagreement is concentrated in a derived quantity: ζ = |Re| / |λ| divides a
small real part by a small natural frequency, so a 3.3e-4 residual in the real
part becomes 0.0019 in the ratio — which is the entire discrepancy, accounted
for but not explained.

Two candidate explanations, neither confirmed:

1. **Terms read as zero that may mean "not supplied".** `X_udot`, `X_wdot`,
   `X_q`, `Z_udot` and `M_udot` are blank in the report's table for this
   aircraft and are taken as zero. `X_q` enters the phugoid directly through
   the `(−X_q + W_o)s` term of Appendix C's first row.
2. **Untranscribed coefficients.** The report's own longitudinal quartic is
   written in terms of `M_alpha` and `M_alpha_dot`, and its `D` and `E`
   coefficients were not transcribed. The phugoid roots are set by the
   low-order coefficients, so an omitted term would show there first.

Until this is resolved the phugoid damping ratio is listed as an open
discrepancy rather than as validated, and a **regression lock** — labelled as
one, per charter rule 8 — holds the gap at its measured size so it cannot grow
unnoticed, and fails if it shrinks, since that would mean the cause has been
found and the lock should become a validation.

)";

  // Version only, deliberately NOT build_identification(): the report is
  // regenerated and diffed by CI on a different compiler and build type from a
  // developer's, and a footer naming the toolchain would make the diff fail for
  // a reason that has nothing to do with the numbers. The provenance of this
  // document is the commit it is committed in.
  std::cout << "---\n\nGenerated from galata " << galata::version_string()
            << " by `tools/validation/report_main.cpp`.\n";
  return 0;
}
