// SPDX-License-Identifier: Apache-2.0
//
// Generates docs/VERIFICATION.md.
//
// The report is generated rather than written because its whole value is that
// its numbers are the numbers the code actually produces. A hand-maintained V&V
// report drifts from the implementation silently, and a drifted V&V report is
// worse than none: it is a document that looks like evidence.
//
// Usage:  galata-validation-report <reference-directory>
// CI regenerates and diffs against the committed file.

#include "galata/analyze/disk_margin.hpp"
#include "galata/analyze/margins.hpp"
#include "galata/analyze/modes.hpp"
#include "galata/core/atmosphere.hpp"
#include "galata/core/quaternion.hpp"
#include "galata/core/state.hpp"
#include "galata/linearize/finite_difference.hpp"
#include "galata/model/aircraft.hpp"
#include "galata/numerics/integrator.hpp"
#include "galata/pipeline/registry.hpp"
#include "galata/sim/rigid_body.hpp"
#include "galata/trim/level.hpp"
#include "galata/units.hpp"
#include "galata/version.hpp"

#include "case_registry.hpp"
#include "fingerprint.hpp"
#include "nt33a_hand_assembly.hpp"
#include "reference_table.hpp"

#include <cmath>
#include <complex>
#include <cstdio>
#include <iostream>
#include <map>
#include <string>
#include <vector>

namespace {

constexpr double kPascalsPerMillibar = 100.0;

struct Deviation {
  double altitude_m = 0.0;
  std::string quantity;
  double published = 0.0;
  double computed = 0.0;
  int significant_figures = 0;
  // How far the computed value sits from the published one, measured in units
  // of the last printed significant figure. Below 0.5 the computed value rounds
  // to exactly what is printed.
  double units_in_last_place = 0.0;
};

double last_place_units(double computed, double published, int significant_figures) {
  if (published == 0.0) {
    return 0.0;
  }
  const double magnitude = std::floor(std::log10(std::fabs(published)));
  const double unit = std::pow(10.0, magnitude - (significant_figures - 1));
  return std::fabs(computed - published) / unit;
}

// ---------------------------------------------------------------------------
// Every number printed below is ROUNDED to a precision that is stable across
// platforms, and that is not cosmetic.
//
// This report is regenerated by CI and diffed against the committed copy. Its
// figures come from running the code, and the code's last digits are NOT
// reproducible across platforms — ADR-0004 tier 2 — because pow, exp and the
// trigonometric functions come from the platform's libm and those do not agree
// in the final bits. A report printing 2.56421e-14 on macOS and 2.56418e-14 on
// Linux would fail its own staleness gate on every push, for a difference that
// carries no information.
//
// So: printed precision is chosen to sit well above the platform spread. It
// also happens to be the honest precision, since quoting six digits of a
// quantity whose last three are toolchain noise overstates what was measured.
// ---------------------------------------------------------------------------

// A vertical bar ends a cell in a Markdown table, so any that appear inside
// generated text must be escaped. Applied to every cell rather than to the one
// note that currently needs it: the notes are prose written by whoever adds a
// case, and "remember to avoid pipes" is not a property anything checks.
std::string escape_table_cell(const std::string& text) {
  std::string escaped;
  escaped.reserve(text.size());
  for (const char character : text) {
    if (character == '|') {
      escaped += "\\|";
    } else {
      escaped += character;
    }
  }
  return escaped;
}

// Replaces every {key} with its measured value.
//
// The point of the mechanism: a number that galata computed must never be typed
// into prose. It is measured once, at render time, and referred to by name
// everywhere it appears — so the summary table, the detail sections and the
// case notes cannot disagree with each other or with the code.
//
// An unresolved placeholder is left in the output deliberately rather than
// silently dropped, and a test greps the rendered document for one.
std::string substitute(const std::string& text,
                       const std::map<std::string, std::string>& measurements) {
  std::string out;
  out.reserve(text.size());
  std::size_t cursor = 0;
  while (cursor < text.size()) {
    const std::size_t open = text.find('{', cursor);
    if (open == std::string::npos) {
      out.append(text, cursor, std::string::npos);
      break;
    }
    const std::size_t close = text.find('}', open);
    if (close == std::string::npos) {
      out.append(text, cursor, std::string::npos);
      break;
    }
    out.append(text, cursor, open - cursor);
    const std::string key = text.substr(open + 1, close - open - 1);
    const auto found = measurements.find(key);
    if (found != measurements.end()) {
      out += found->second;
    } else {
      // Left visible on purpose. A silently dropped placeholder is a sentence
      // that reads fine and says nothing.
      out += "{UNRESOLVED:" + key + "}";
    }
    cursor = close + 1;
  }
  return out;
}

// Fixed number of significant figures.
std::string format_significant(double value, int figures) {
  char buffer[64];
  std::snprintf(buffer, sizeof(buffer), "%.*g", figures, value);
  return buffer;
}

// Three significant figures: far coarser than the ~1e-16 relative spread
// between platforms, fine enough to see a real change.
std::string format(double value) {
  return format_significant(value, 3);
}

// An upper bound rounded up to the next power of ten.
//
// Used for drift figures, whose exact value is meaningless at this magnitude —
// what matters is the order, and an order is stable across platforms in a way
// a mantissa is not.
std::string format_bound(double value) {
  if (!(value > 0.0)) {
    return "0";
  }
  const double exponent = std::ceil(std::log10(value));
  char buffer[64];
  std::snprintf(buffer, sizeof(buffer), "below 1e%+d", static_cast<int>(exponent));
  return buffer;
}

// One published quantity against the value galata computes for it.
struct Comparison {
  std::string name;
  double computed = 0.0;
  double published = 0.0;

  [[nodiscard]] double relative() const {
    return (published == 0.0) ? 0.0 : std::fabs(computed - published) / std::fabs(published);
  }
};

std::string percent(double relative) {
  char buffer[64];
  std::snprintf(buffer, sizeof(buffer), "%.2f%%", 100.0 * relative);
  return buffer;
}

// Everything the report states about the NT-33A, computed rather than recalled.
struct Nt33aMeasurements {
  galata::trim::TrimPoint trim;
  std::vector<Comparison> lateral_derivatives;
  std::vector<Comparison> modes;
  double worst_derivative_relative = 0.0;
  double worst_mode_relative = 0.0;
  std::string worst_mode_name;
  // The hand-assembled route, for the discrepancy section.
  double hand_phugoid_zeta = 0.0;
  double hand_phugoid_real = 0.0;
  double hand_phugoid_imag = 0.0;
  // Weakest and strongest evidence behind any label the chain assigns.
  double min_label_score = 1.0;
  double max_label_score = 0.0;
};

Nt33aMeasurements measure_nt33a(const std::map<std::string, double>& published,
                                const std::string& model_path) {
  using galata::analyze::analyze_modes;
  using galata::analyze::ModeLabel;
  using galata::analyze::StateRoles;

  Nt33aMeasurements out;

  const galata::model::Aircraft aircraft = galata::model::load_aircraft(model_path);
  galata::trim::LevelTrimRequest request;
  request.altitude_m = 0.0;
  request.airspeed_m_s = galata::units::feet_to_metres(published.at("true_airspeed"));
  out.trim = galata::trim::trim_level(aircraft, request);

  galata::linearize::LinearisationOptions lateral_options;
  lateral_options.state_subset = galata::linearize::lateral_states();
  const auto lateral =
      galata::linearize::linearize_finite_difference(aircraft, out.trim, lateral_options);
  galata::linearize::LinearisationOptions longitudinal_options;
  longitudinal_options.state_subset = galata::linearize::longitudinal_states();
  const auto longitudinal =
      galata::linearize::linearize_finite_difference(aircraft, out.trim, longitudinal_options);

  // The state is [v, p, r, phi] and the report's is [beta, p, r, phi]; they
  // differ by a similarity transform with S = diag(1/V, 1, 1, 1), which touches
  // only the first row and column and leaves the eigenvalues alone.
  const double speed = out.trim.airspeed_m_s;
  out.lateral_derivatives = {
      {"Y_v", lateral.a(0, 0), published.at("Y_v")},
      {"L_beta'", lateral.a(1, 0) * speed, published.at("L_beta_prime")},
      {"N_beta'", lateral.a(2, 0) * speed, published.at("N_beta_prime")},
      {"L_p'", lateral.a(1, 1), published.at("L_p_prime")},
      {"N_p'", lateral.a(2, 1), published.at("N_p_prime")},
      {"L_r'", lateral.a(1, 2), published.at("L_r_prime")},
      {"N_r'", lateral.a(2, 2), published.at("N_r_prime")},
  };
  for (const Comparison& comparison : out.lateral_derivatives) {
    out.worst_derivative_relative = std::fmax(out.worst_derivative_relative, comparison.relative());
  }

  const auto lateral_modes =
      analyze_modes(lateral.a, lateral.state_names, StateRoles::from_names(lateral.state_names));
  const auto longitudinal_modes = analyze_modes(
      longitudinal.a, longitudinal.state_names, StateRoles::from_names(longitudinal.state_names));

  const auto* spiral = lateral_modes.find(ModeLabel::Spiral);
  const auto* roll = lateral_modes.find(ModeLabel::RollSubsidence);
  const auto* dutch = lateral_modes.find(ModeLabel::DutchRoll);
  const auto* phugoid = longitudinal_modes.find(ModeLabel::Phugoid);
  const auto* short_period = longitudinal_modes.find(ModeLabel::ShortPeriod);
  if (spiral == nullptr || roll == nullptr || dutch == nullptr || phugoid == nullptr
      || short_period == nullptr) {
    throw std::runtime_error(
        "galata-validation-report: the NT-33A chain did not produce all five classical modes, "
        "so the report cannot state what it agrees with");
  }

  out.modes = {
      {"Phugoid zeta", phugoid->damping_ratio, published.at("phugoid_damping_ratio")},
      {"Phugoid omega_n",
       phugoid->natural_frequency_rad_s,
       published.at("phugoid_natural_frequency")},
      {"Short period zeta",
       short_period->damping_ratio,
       published.at("short_period_damping_ratio")},
      {"Short period omega_n",
       short_period->natural_frequency_rad_s,
       published.at("short_period_natural_frequency")},
      {"Spiral 1/T", -spiral->eigenvalue.real(), published.at("spiral_root")},
      {"Roll subsidence 1/T", -roll->eigenvalue.real(), published.at("roll_subsidence_root")},
      {"Dutch roll zeta", dutch->damping_ratio, published.at("dutch_roll_damping_ratio")},
      {"Dutch roll omega_n",
       dutch->natural_frequency_rad_s,
       published.at("dutch_roll_natural_frequency")},
  };
  for (const Comparison& comparison : out.modes) {
    if (comparison.relative() > out.worst_mode_relative) {
      out.worst_mode_relative = comparison.relative();
      out.worst_mode_name = comparison.name;
    }
  }

  // The hand-assembled route, from the same shared assembly the regression lock
  // tests, so the two cannot describe different matrices.
  const auto hand_inputs = galata::validation::HandAssemblyInputs::from_published(published);
  const auto hand_names = galata::validation::longitudinal_state_names();
  const auto hand_modes =
      analyze_modes(galata::validation::hand_assembled_longitudinal(hand_inputs),
                    hand_names,
                    StateRoles::from_names(hand_names));
  const auto* hand_phugoid = hand_modes.find(ModeLabel::Phugoid);
  if (hand_phugoid == nullptr) {
    throw std::runtime_error(
        "galata-validation-report: the hand-assembled matrix produced no phugoid");
  }
  for (const auto* modes : {&lateral_modes, &longitudinal_modes}) {
    for (const auto& mode : modes->modes) {
      out.min_label_score = std::fmin(out.min_label_score, mode.label_score);
      out.max_label_score = std::fmax(out.max_label_score, mode.label_score);
    }
  }

  out.hand_phugoid_zeta = hand_phugoid->damping_ratio;
  out.hand_phugoid_real = hand_phugoid->eigenvalue.real();
  out.hand_phugoid_imag = hand_phugoid->eigenvalue.imag();
  return out;
}

}  // namespace

int main(int argc, char** argv) {
  if (argc != 2) {
    std::cerr << "usage: galata-validation-report <reference-directory>\n";
    return 2;
  }
  const std::string reference_dir = argv[1];

  galata::testing::ReferenceTable table;
  try {
    table = galata::testing::load_reference(reference_dir, "ussa1976.csv");
  } catch (const std::exception& error) {
    std::cerr << "galata-validation-report: " << error.what() << "\n";
    return 1;
  }

  std::vector<Deviation> deviations;
  double worst_temperature = 0.0;
  double worst_pressure = 0.0;
  double worst_density = 0.0;
  double worst_sound = 0.0;

  for (std::size_t row = 0; row < table.rows.size(); ++row) {
    const double altitude = table.at(row, "geometric_altitude_m");
    const galata::core::AtmosphereState computed = galata::core::isa(altitude);

    struct Case {
      const char* name;
      double published;
      double computed;
      int figures;
      double* worst;
    };

    const Case cases[] = {
        {"temperature",
         table.at(row, "temperature_k"),
         computed.temperature_k,
         static_cast<int>(table.at(row, "temperature_sig_figs")),
         &worst_temperature},
        {"pressure",
         table.at(row, "pressure_mb"),
         computed.pressure_pa / kPascalsPerMillibar,
         static_cast<int>(table.at(row, "pressure_sig_figs")),
         &worst_pressure},
        {"density",
         table.at(row, "density_kg_m3"),
         computed.density_kg_m3,
         static_cast<int>(table.at(row, "density_sig_figs")),
         &worst_density},
        {"speed of sound",
         table.at(row, "speed_of_sound_m_s"),
         computed.speed_of_sound_m_s,
         static_cast<int>(table.at(row, "speed_of_sound_sig_figs")),
         &worst_sound},
    };

    for (const Case& c : cases) {
      const double ulp = last_place_units(c.computed, c.published, c.figures);
      if (ulp > *c.worst) {
        *c.worst = ulp;
      }
      if (ulp > 0.5) {
        deviations.push_back({altitude, c.name, c.published, c.computed, c.figures, ulp});
      }
    }
  }

  // ---------------------------------------------------------------------------
  // Everything the document states as a number, measured here, once.
  //
  // No figure below this line is typed into prose anywhere in this file or in
  // the case registry. Prose refers to them by {name}; a test greps the
  // rendered document for an unresolved placeholder, and another asserts that
  // no case note contains one of these values as a literal.
  // ---------------------------------------------------------------------------
  Nt33aMeasurements nt33a;
  std::map<std::string, double> published_nt33a;
  galata::determinism::Counts fingerprint_counts;
  try {
    published_nt33a = galata::testing::load_reference(reference_dir, "nt33a_fc1.csv")
                          .as_lookup("quantity", "value");
    nt33a = measure_nt33a(published_nt33a, std::string(GALATA_REPORT_MODEL));
    fingerprint_counts = galata::determinism::fingerprint_counts(std::string(GALATA_REPORT_MODEL));
  } catch (const std::exception& error) {
    std::cerr << "galata-validation-report: " << error.what() << "\n";
    return 1;
  }

  std::map<std::string, std::string> measured;
  measured["atm.deviating"] = std::to_string(deviations.size());
  measured["atm.total"] = std::to_string(table.rows.size() * 4U);
  measured["atm.worst_ulp"] = format(std::fmax(std::fmax(worst_temperature, worst_pressure),
                                               std::fmax(worst_density, worst_sound)));
  measured["atm.worst_temperature"] = format(worst_temperature);
  measured["atm.worst_pressure"] = format(worst_pressure);
  measured["atm.worst_density"] = format(worst_density);
  measured["atm.worst_sound"] = format(worst_sound);

  {
    // The source prints Sutherland's constant as both 110 K and 110.4 K. How
    // much that ambiguity is worth is a property of the equation, so it is
    // computed rather than remembered.
    const galata::core::AtmosphereState sea_level = galata::core::isa(0.0);
    const double t = sea_level.temperature_k;
    const double with_110_4 =
        galata::core::ussa1976::kSutherlandBeta * t * std::sqrt(t) / (t + 110.4);
    const double with_110 =
        galata::core::ussa1976::kSutherlandBeta * t * std::sqrt(t) / (t + 110.0);
    measured["atm.viscosity_s_percent"] = percent(std::fabs(with_110 - with_110_4) / with_110_4);
    measured["atm.tm_86km"] = format_significant(galata::core::isa(86000.0).temperature_k, 6);
  }

  measured["trim.alpha_deg"] =
      format_significant(galata::units::radians_to_degrees(nt33a.trim.alpha_rad), 5);
  measured["trim.published_alpha_deg"] = format_significant(published_nt33a.at("trim_alpha"), 3);
  measured["trim.alpha_shift_deg"] = format(galata::units::radians_to_degrees(
      galata::units::degrees_to_radians(published_nt33a.at("trim_alpha")) - nt33a.trim.alpha_rad));
  {
    // Pounds per square foot, converted at the boundary.
    const double pascals_per_psf =
        galata::units::kNewtonsPerPoundForce
        / (galata::units::kMetresPerFoot * galata::units::kMetresPerFoot);
    measured["trim.psf"] = format_significant(nt33a.trim.dynamic_pressure_pa / pascals_per_psf, 4);
  }
  measured["trim.published_psf"] = format_significant(published_nt33a.at("dynamic_pressure"), 3);
  measured["trim.mach"] = format_significant(nt33a.trim.mach, 4);
  measured["trim.published_mach"] = format_significant(published_nt33a.at("mach"), 3);
  measured["trim.cl"] = format_significant(nt33a.trim.lift_coefficient, 4);
  measured["trim.published_cl"] = format_significant(published_nt33a.at("CL"), 3);
  measured["trim.residual"] = format_bound(nt33a.trim.residual_norm);
  measured["trim.thrust_n"] = format_significant(nt33a.trim.controls.thrust_n, 5);

  measured["deriv.worst_percent"] = percent(nt33a.worst_derivative_relative);
  measured["modes.worst_percent"] = percent(nt33a.worst_mode_relative);
  measured["modes.worst_name"] = nt33a.worst_mode_name;

  measured["hand.phugoid_zeta"] = format_significant(nt33a.hand_phugoid_zeta, 3);
  measured["hand.phugoid_real"] = format_significant(nt33a.hand_phugoid_real, 5);
  measured["hand.phugoid_imag"] = format_significant(nt33a.hand_phugoid_imag, 6);
  {
    const double published_zeta = published_nt33a.at("phugoid_damping_ratio");
    const double published_omega = published_nt33a.at("phugoid_natural_frequency");
    measured["hand.phugoid_percent"] =
        percent(std::fabs(nt33a.hand_phugoid_zeta - published_zeta) / published_zeta);
    measured["published.phugoid_real"] = format_significant(-published_zeta * published_omega, 5);
    measured["published.phugoid_imag"] =
        format_significant(published_omega * std::sqrt(1.0 - published_zeta * published_zeta), 6);
    // The chain's phugoid, for the side-by-side.
    for (const Comparison& comparison : nt33a.modes) {
      if (comparison.name == "Phugoid zeta") {
        measured["chain.phugoid_zeta"] = format_significant(comparison.computed, 3);
        measured["chain.phugoid_percent"] = percent(comparison.relative());
      }
    }
  }

  // The standard states its ceiling twice and the two disagree; by how much is
  // a property of equation (18), not a remembered number.
  measured["atm.ceiling_geopotential"] =
      format_significant(galata::core::geopotential_from_geometric(86000.0), 8);
  {
    // How far the molecular-scale temperature departs from the tabulated
    // kinetic one at the top of the model.
    const double tabulated_kinetic = 186.87;  // Table I at Z = 86 km, transcribed
    measured["atm.tm_departure_k"] =
        format(galata::core::isa(86000.0).temperature_k - tabulated_kinetic);
  }
  {
    // The stability-to-body rotation "looks like a cos(alpha) effect". How
    // small that would be, and how much bigger the cross term is, are both
    // properties of the published derivative set.
    const double alpha = galata::units::degrees_to_radians(published_nt33a.at("trim_alpha"));
    measured["axes.cos_alpha"] = format_significant(std::cos(alpha), 4);
    measured["axes.cos_effect_percent"] = percent(1.0 - std::cos(alpha));
    measured["axes.beta_ratio"] =
        format(std::fabs(published_nt33a.at("Cl_beta") / published_nt33a.at("Cn_beta")));
  }
  measured["chain.min_label_score"] = format(nt33a.min_label_score);
  measured["chain.max_label_score"] = format(nt33a.max_label_score);
  {
    const galata::determinism::Amplification amplification =
        galata::determinism::amplification_study();
    measured["fingerprint.min_amplification"] = format(amplification.smallest);
    measured["fingerprint.max_amplification"] = format(amplification.largest);
  }

  // --- The disk-margin worked example ---------------------------------------
  //
  // Recomputed here rather than quoted, so that every disk-margin number in
  // this document and in the case notes is a number this build produced. The
  // loop is the one the tutorial states:
  //   L(s) = 25 / (s^3 + 10 s^2 + 10 s + 10)
  {
    const galata::analyze::LoopEvaluator loop = [](double w) {
      const std::complex<double> s{0.0, w};
      return 25.0 / (s * s * s + 10.0 * s * s + 10.0 * s + 10.0);
    };
    galata::analyze::MarginOptions options;
    options.start_rad_s = 1.0e-2;
    options.stop_rad_s = 1.0e3;
    options.grid_points = 4000;

    const auto disk = galata::analyze::disk_margin(loop, 0.0, options);
    const auto classical = galata::analyze::stability_margins(loop, options);

    measured["disk.alpha"] = format_significant(disk.alpha, 5);
    measured["disk.peak"] = format_significant(disk.peak_gain, 5);
    measured["disk.omega0"] = format_significant(disk.critical_frequency_rad_s, 5);
    measured["disk.gamma_min"] = format_significant(disk.gain_variation_min, 5);
    measured["disk.gamma_max"] = format_significant(disk.gain_variation_max, 5);
    measured["disk.phi_m"] = format_significant(disk.phase_variation_deg, 6);
    measured["disk.classical_gm"] = format_significant(classical.gain_margin, 5);
    measured["disk.classical_pm"] = format_significant(classical.phase_margin_deg, 6);

    // How far the paper's PRINTED critical frequency is from reproducing the
    // paper's own printed delta_0, expressed in units of delta_0's last
    // printed figure. A unit in the last figure of 0.212 is 0.001.
    constexpr double kPrintedOmega0 = 1.94;
    constexpr double kPrintedDeltaReal = 0.212;
    constexpr double kUnitInLastFigure = 0.001;
    const std::complex<double> sensitivity_at_printed = 1.0 / (1.0 + loop(kPrintedOmega0));
    const double delta_real_at_printed = (1.0 / (sensitivity_at_printed - 0.5)).real();
    measured["disk.omega0_units_off"] = format_significant(
        std::fabs(delta_real_at_printed - kPrintedDeltaReal) / kUnitInLastFigure, 3);
    measured["disk.delta_real_at_printed"] = format_significant(delta_real_at_printed, 4);
  }

  measured["det.total"] = std::to_string(fingerprint_counts.total);
  measured["det.tier1_only"] = std::to_string(fingerprint_counts.tier1_only);
  measured["det.cross_platform"] = std::to_string(fingerprint_counts.cross_platform());

  {
    // What a log-slope fit measures on a cosh over the window the earlier,
    // wrong version of the intermediate-axis test used. A property of cosh, so
    // computed rather than quoted.
    const double early = 0.375;
    const double late = 1.5;
    measured["cosh.slope_factor"] =
        format(std::log(std::cosh(late) / std::cosh(early)) / (late - early));
  }

  // A value galata computed must be referred to by name, never typed. This
  // catches the specific mistake of running the report, seeing a number, and
  // pasting it into a note — which reads identically to using the placeholder
  // and stops being true the moment anything changes.
  //
  // Only values of four characters or more are checked. A count like "3" would
  // match half the prose in the document, and a false positive here blocks the
  // build for no reason.
  {
    bool hardcoded = false;
    for (const auto& [key, value] : measured) {
      if (value.size() < 4) {
        continue;
      }
      for (const auto& validation_case : galata::validation::validation_cases()) {
        if (validation_case.note.find(value) != std::string::npos) {
          std::cerr << "galata-validation-report: case '" << validation_case.id
                    << "' hard-codes the value '" << value << "', which this report computes as {"
                    << key << "}. Use the placeholder.\n";
          hardcoded = true;
        }
      }
    }
    if (hardcoded) {
      return 1;
    }
  }

  std::cout << R"(<!-- GENERATED FILE — DO NOT EDIT.
     Produced by tools/validation/report_main.cpp via scripts/gen-verification.sh.
     CI regenerates this file and fails if it differs from the committed copy,
     so every number below is a number the code actually produced. -->

# Verification and validation

What galata has been checked against, what agreement was measured, and what has
not been checked at all.

The last column is the one to read. "Unvalidated" is not a placeholder here — it
is a statement that no published reference value has been found for that case,
and it is preferred to a number invented to fill the gap.

## Summary

The table below is GENERATED from `tools/validation/case_registry.cpp` and is
reconciled against the capability registry the CLI dispatches through. It used
to be typed by hand and it drifted three times, most memorably by still saying
"there is no aerodynamic model yet" in the commit that added one.

Four checks stand behind it, each a test rather than a convention:

* every case claiming a comparison names a reference and names its evidence;
* every piece of evidence names a test that is **actually registered** in the
  binary the case says it lives in, so a renamed or deleted test breaks the
  build rather than leaving a fictional citation;
* every capability declaring *implemented and validated* is backed by at least
  one validating case, which makes that declaration unfalsifiable by hand;
* a case marked *not implemented* may not name a capability that exists, so
  the row cannot outlive the thing being built.

| Case | Reference | Status |
|---|---|---|
)";

  for (const auto& validation_case : galata::validation::validation_cases()) {
    std::cout << "| " << escape_table_cell(validation_case.title) << " | "
              << (validation_case.reference.empty() ? "—"
                                                    : escape_table_cell(validation_case.reference))
              << " | " << galata::validation::to_string(validation_case.status);
    if (!validation_case.note.empty()) {
      std::cout << " — " << escape_table_cell(substitute(validation_case.note, measured));
    }
    std::cout << " |\n";
  }

  // --- Evidence -------------------------------------------------------------
  std::cout << R"(
### Evidence

Every case above, and the tests that stand behind it. These names are checked
against the tests actually registered in each binary, so they can be run:

```
ctest --preset dev -R '<test name>'
```

| Case | Evidence |
|---|---|
)";
  for (const auto& validation_case : galata::validation::validation_cases()) {
    std::cout << "| " << escape_table_cell(validation_case.title) << " | ";
    if (validation_case.evidence.empty()) {
      std::cout << "— |\n";
      continue;
    }
    bool first = true;
    for (const auto& evidence : validation_case.evidence) {
      if (!first) {
        std::cout << "<br>";
      }
      std::cout << "`" << evidence.test << "` (" << galata::validation::to_string(evidence.binary)
                << ")";
      first = false;
    }
    std::cout << " |\n";
  }

  // --- Reconciliation with the capability registry --------------------------
  std::cout << R"(
### Capabilities, and the cases that validate them

Read straight out of the registry the CLI dispatches through, so a capability
cannot appear here without existing, and cannot claim validation without a case
backing it. A capability may legitimately be *implemented, unvalidated* — that
is an honest state, and it means no published reference has been compared
against.

| Capability | Declared state | Validated by |
|---|---|---|
)";
  for (const auto* capability : galata::pipeline::builtin_registry().all()) {
    std::cout << "| `" << capability->id << "` | " << galata::pipeline::to_string(capability->state)
              << " | ";
    std::vector<std::string> backing;
    for (const auto& validation_case : galata::validation::validation_cases()) {
      if (!galata::validation::claims_a_comparison(validation_case.status)) {
        continue;
      }
      for (const std::string& named : validation_case.capabilities) {
        if (named == capability->id) {
          backing.push_back(validation_case.id);
        }
      }
    }
    if (backing.empty()) {
      std::cout << "— |\n";
    } else {
      for (std::size_t i = 0; i < backing.size(); ++i) {
        std::cout << (i == 0 ? "" : ", ") << "`" << backing[i] << "`";
      }
      std::cout << " |\n";
    }
  }
  std::cout << "\n";

  std::cout << "## U.S. Standard Atmosphere, 1976\n\n";
  std::cout << "**Reference.** U.S. Committee on Extension to the Standard Atmosphere (COESA),\n"
               "*U.S. Standard Atmosphere, 1976*, NOAA-S/T 76-1562 / NASA-TM-X-74335,\n"
               "U.S. Government Printing Office, October 1976.\n"
               "NTRS document 19770009539, <https://ntrs.nasa.gov/citations/19770009539>.\n"
               "Rights: *Work of the US Gov. Public Use Permitted.*\n\n";

  std::cout
      << "**Transcription.** The NTRS scan's OCR layer is unusable for numeric tables —\n"
         "roughly 95,800 extractable characters across 243 pages, with digits rendered as\n"
         "underscores and letters. No value came from it. The page images were extracted and\n"
         "read visually, with load-bearing digits re-cropped at native resolution, and a\n"
         "second independent pass re-read twelve values without reference to the first.\n"
         "The full method is in the header of `tests/validation/reference/ussa1976.csv`.\n\n";

  std::cout << "**Agreement measured.** Deviation is given in units of the last printed\n"
               "significant figure. Below 0.5 the computed value rounds to exactly what the\n"
               "document prints.\n\n";

  std::cout << "| Quantity | Worst deviation (units in last printed place) | Rounds to the printed "
               "value everywhere |\n";
  std::cout << "|---|---|---|\n";

  const struct {
    const char* name;
    double worst;
  } summary[] = {
      {"Temperature", worst_temperature},
      {"Pressure", worst_pressure},
      {"Density", worst_density},
      {"Speed of sound", worst_sound},
  };

  for (const auto& entry : summary) {
    std::cout << "| " << entry.name << " | " << format(entry.worst) << " | "
              << (entry.worst <= 0.5 ? "yes" : "**no**") << " |\n";
  }

  std::cout << "\n**Gate.** The validation suite requires every cell to agree within 1.0 units of\n"
               "the last printed place. That bound is chosen to be the tightest one the 1976\n"
               "tables actually support, not the loosest one that passes: the measured\n"
               "disagreements are around one part in 10^5, while a wrong lapse-rate sign, a\n"
               "geopotential/geometric mix-up or the wrong Earth radius each move these values by\n"
               "one part in 10^2 or worse.\n\n";

  if (deviations.empty()) {
    std::cout << "Every tabulated cell rounds to the printed value.\n\n";
  } else {
    std::cout << "### Cells that do not round to the printed value\n\n";
    std::cout << "There are " << deviations.size() << " of them, out of " << (table.rows.size() * 4)
              << " tabulated cells.\n\n";
    std::cout
        << "| Geometric altitude (m) | Quantity | Published | Computed | Units in last place |\n";
    std::cout << "|---|---|---|---|---|\n";
    for (const Deviation& d : deviations) {
      // Both values at the precision the source prints, which is the only
      // precision at which the comparison means anything.
      std::cout << "| " << format_significant(d.altitude_m, 6) << " | " << d.quantity << " | "
                << format_significant(d.published, d.significant_figures) << " | "
                << format_significant(d.computed, d.significant_figures) << " | "
                << format(d.units_in_last_place) << " |\n";
    }
    std::cout << "\n";
  }

  std::cout << substitute(R"(### Known model-versus-table differences that are not errors

**Molecular-scale versus kinetic temperature above 80 km.** The seven-layer
system is defined in terms of molecular-scale temperature `T_M`, which equals
kinetic temperature `T` only where the mean molecular weight equals its
sea-level value. Above roughly 80 km the ratio `M/M_0` falls away from 1 — the
document's Table 8 gives 0.9995788 at 86 km — so galata's temperature runs high
relative to the tabulated kinetic temperature by {atm.tm_departure_k} K in the top
6 km. At 86 km the document tabulates `T = 186.87` K and `T_M = 186.95` K;
galata computes {atm.tm_86km} K, which is the `T_M` value.

**The upper bound is stated twice and the two statements differ.** The standard
gives the ceiling as both 84.8520 km' geopotential and 86 km geometric.
Equation (18) maps 86000 m to {atm.ceiling_geopotential} m', so the geopotential figure is the
document's own rounding. galata bounds the envelope in geometric altitude, so
that a query at exactly the standard's stated ceiling is accepted.

### Ambiguities in the source document

These are inconsistencies in the 1976 publication itself, found during
transcription. Each is recorded so that it is not later mistaken for a
transcription error.

| Quantity | Printed as | And also as | galata uses |
|---|---|---|---|
| Sutherland's constant `S` | 110 K (Table 2B, printed page 4) | 110.4 K (text at equation (51)) | 110.4 K, the value stated with the equation it parameterises |
| `R*` | 8.31432e3 N m/(kmol K) (body text, printed page 3) | 8.31432e-3 (Table 2A) | 8.31432e3; only this makes equations (33a)/(33b) dimensionally consistent |
| Sutherland's `beta` | 1.458e-6 (Table 2B, printed page 19) | 1.458e6 (printed page 4, minus sign absent) | 1.458e-6, corroborated twice |
| `r_0` | 6,356,766 m (printed page 8) | 6356.766 km (printed page 4) | 6356766 m; Table 2B's exponent glyph is illegible in the available scans and was not used |

### What is not validated here

**Dynamic viscosity.** galata implements equation (51), but no tabulated
viscosity values were transcribed from the document, so there is nothing to
compare against. The implementation is unvalidated. It additionally inherits the
`S = 110` versus `S = 110.4` ambiguity above, which moves the result by
{atm.viscosity_s_percent}.

**Altitudes between the tabulated points.** Eight altitudes are checked against
the tables. Continuity, monotonicity and the absence of steps at layer
boundaries are checked on a 100 m grid across the whole envelope, which
constrains the space between the sampled points but is not the same as checking
it against published values.

**Everything above 86 km.** Out of scope: galata refuses the query rather than
extrapolating.

)",
                          measured);

  std::cout << substitute(R"(## Determinism

ADR-0004 defines two tiers, and both are gated by
`.github/workflows/determinism.yml` on Linux, macOS and Windows.

**Tier 1 — same binary, same platform, byte-identical.** `tools/determinism`
emits 92 values at `%.17g`, which round-trips a double exactly, so byte-identical
output means bit-identical values rather than values that merely print the same.
Gated absolutely on every platform.

**Tier 2 — cross-platform, bounded.** Every platform PAIR is compared, not each
against a nominated reference: with a reference, which platform holds that role
is an arbitrary choice that then shows up in the published numbers. The gate is
1e-9 relative — far above the roughly 1e-16 that one math-library call costs,
far below the roughly 1e-5 that any real divergence in the physics would
produce, so it discriminates between "different libm" and "different answer".

The observed deviation is printed by every run rather than merely bounded; read
it from the workflow log. It is not restated here, because a measured figure
copied into a hand-maintained document is a figure that drifts.

**Why tier 2 is not bit-identity.** `sqrt` is required by IEEE 754 to be
correctly rounded and agrees everywhere. `sin`, `cos`, `tan`, `asin`, `atan2`,
`exp`, `log` and `pow` are not, and come from the platform's math library.
galata cannot avoid them — angle of attack is an `atan2`, the atmosphere's
pressure profile is a `pow` — so the honest claim is the two-tier one rather
than a bit-identity claim that would be false.

**A constraint on what may be fingerprinted.** A cross-platform bound is only
meaningful on a computation that does not amplify small differences; on a
chaotic trajectory the gate would be measuring chaos rather than agreement. The
fingerprint's rigid-body case was measured and amplifies a perturbation by a
factor between {fingerprint.min_amplification} and {fingerprint.max_amplification} over
60 s. A test asserts this, so a change that makes the battery chaotic fails
there rather than as an intermittently red workflow.

)",
                          measured);

  std::cout << substitute(R"(## Trim and linearisation

**Reference.** Heffley and Jewell, NASA CR-2144, Tables II-1, II-2 and II-7.

This is the end-to-end case, and it is a much stronger statement than the modal
comparison above. There, the state matrix came from the report's own
dimensional derivatives, so only the eigen-analysis was under test. Here the
input is the NON-dimensional derivative set and the geometry; galata builds a
nonlinear model, finds its trim, linearises about it, and both the dimensional
derivatives and the modes fall out. Everything in between is under test: the
atmosphere, every unit conversion, the coefficient buildup, the wind-to-body
rotation, the equations of motion, the root-find and the finite differences.

**Trim.** Converges to a residual of {trim.residual}, with quadratic
convergence visible in the reported history. It is checked two ways: against
the closed-form force balance `L = mg - D tan(a)` and `T = D/cos(a)`, which it
satisfies to a part in 10^6; and against the published flight condition.

| Quantity | galata | published |
|---|---|---|
| Dynamic pressure | {trim.psf} psf | {trim.published_psf} psf |
| Mach | {trim.mach} | {trim.published_mach} |
| Trim lift coefficient | {trim.cl} | {trim.published_cl} |
| Angle of attack | {trim.alpha_deg} deg | {trim.published_alpha_deg} deg |

The trimmed angle of attack sits {trim.alpha_shift_deg} deg below the published
value, and the difference is understood rather than tolerated. The published
pair (alpha and C_L) is related by the conventional level-flight relation
C_L = W/(qS), which neglects the vertical component of drag in body axes.
galata solves the exact balance, which needs a slightly smaller C_L. The shift
is exactly `D tan(a)/(qS)/C_L_alpha`, and a test asserts it is that term and
nothing else.

**Linearised dimensional derivatives** against Table II-7 — seven numbers the
report computed from the same non-dimensional set by a different route:

| Derivative | galata | published | difference |
|---|---|---|---|
)",
                          measured);

  for (const Comparison& comparison : nt33a.lateral_derivatives) {
    std::cout << "| " << comparison.name << " | " << format_significant(comparison.computed, 6)
              << " | " << format_significant(comparison.published, 6) << " | "
              << percent(comparison.relative()) << " |\n";
  }

  std::cout << substitute(R"(
The source prints its inputs and its outputs to three significant figures, so
each carries up to about 0.5% of its own rounding and several combine in every
one of these. The gate is 0.5%; the worst observed is {deriv.worst_percent}.

**All five modes**, from the same linearisation:

| Mode | galata | published | difference |
|---|---|---|---|
)",
                          measured);

  for (const Comparison& comparison : nt33a.modes) {
    std::cout << "| " << comparison.name << " | " << format_significant(comparison.computed, 5)
              << " | " << format_significant(comparison.published, 4) << " | "
              << percent(comparison.relative()) << " |\n";
  }

  std::cout << substitute(R"(
The worst is {modes.worst_name} at {modes.worst_percent}.

**An error this comparison caught.** The first version of the model treated the
report's lateral derivatives as body-axis when the report gives them in
stability axes. At a trim angle of attack of about two degrees that looks like a
{axes.cos_effect_percent} effect, since cos(alpha) = {axes.cos_alpha}. It is not: the
rotation MIXES the rolling and yawing moments, and C_l_beta is {axes.beta_ratio}
times C_n_beta, so the cross
term dominates and C_n_beta moves by 10%. The Dutch roll damping came out 35%
high. It was the derivative-by-derivative comparison above that localised it —
the modes alone said only that something was wrong.

A second error was found the same way: the force assembly rotated the
lift/drag/side triple through the full wind-axis rotation, which adds a
`-D sin(beta)` term to the body y force that a body-axis C_Y_beta already
contains. Double-counting it inflated the side-force derivative by 19%.

Both are the reason `models/nt33a/nt33a-fc1.yaml` must DECLARE which axes its
lateral derivatives are in, rather than defaulting.

)",
                          measured);

  // --- Rigid-body dynamics, measured -----------------------------------
  {
    using galata::core::State;
    using galata::core::StateVector;
    using galata::sim::MassProperties;
    using galata::sim::Wrench;

    // Asymmetric body with a non-zero product of inertia, so the general
    // tensor path is what is measured rather than a convenient special case.
    MassProperties mass;
    mass.mass_kg = 4000.0;
    mass.inertia_cg_body_kg_m2 << 12000.0, 0.0, -1500.0,  //
        0.0, 40000.0, 0.0,                                //
        -1500.0, 0.0, 48000.0;

    State initial;
    initial.attitude_body_to_ned = galata::core::quaternion_from_euler({0.3, -0.2, 1.1});
    initial.angular_rate_body_rad_s = Eigen::Vector3d(0.9, -0.4, 0.6);

    const galata::numerics::DerivativeFunction derivative =
        [&mass](double, const Eigen::VectorXd& x) -> Eigen::VectorXd {
      return galata::sim::rigid_body_derivative(
          State::from_vector(StateVector(x)), mass, Wrench{}, Eigen::Vector3d::Zero());
    };
    const galata::numerics::ProjectionFunction project = [](Eigen::VectorXd& x) {
      State state = State::from_vector(StateVector(x));
      state.renormalise_attitude();
      x = state.to_vector();
    };

    const double energy_0 = galata::sim::rotational_kinetic_energy(initial, mass);
    const Eigen::Vector3d momentum_0 = galata::sim::angular_momentum_ned(initial, mass);

    const double step = 1e-3;
    const int steps = 60000;  // 60 s
    const auto trajectory = galata::numerics::integrate_fixed_step(
        derivative, initial.to_vector(), 0.0, step, steps, 100, project);

    double worst_energy = 0.0;
    double worst_momentum = 0.0;
    for (const Eigen::VectorXd& raw : trajectory.states) {
      const State state = State::from_vector(StateVector(raw));
      worst_energy = std::fmax(
          worst_energy,
          std::fabs(galata::sim::rotational_kinetic_energy(state, mass) - energy_0) / energy_0);
      worst_momentum = std::fmax(
          worst_momentum,
          (galata::sim::angular_momentum_ned(state, mass) - momentum_0).norm() / momentum_0.norm());
    }

    std::cout << R"(## Rigid-body dynamics

**Reference.** These cases carry no transcribed numbers: the reference is an
analytic solution of Euler's equations, with the derivation written out in
`tests/validation/test_rigid_body_dynamics.cpp` so a reader can check it against
the equations rather than against a table. That makes them the strongest
validation in the suite — there is no transcription step to get wrong, and the
expected values are exact rather than rounded.

H. Goldstein, C. P. Poole and J. L. Safko, *Classical Mechanics*, 3rd ed.,
Addison Wesley, 2002; L. D. Landau and E. M. Lifshitz, *Mechanics*, 3rd ed.,
Butterworth-Heinemann, 1976.

**Conservation under torque-free motion.** Asymmetric body with a non-zero
product of inertia, 60 s of integration at a 1 ms fixed step — 60,000 RK4 steps.

| Invariant | Worst relative drift over 60 s |
|---|---|
)";
    std::cout << "| Rotational kinetic energy | " << format_bound(worst_energy) << " |\n";
    std::cout << "| Angular momentum vector, resolved in NED | " << format_bound(worst_momentum)
              << " |\n";

    std::cout << R"(
The angular-momentum figure is the vector in the NAVIGATION frame, not its
magnitude in body axes. That is deliberate and it is the stronger claim: the
magnitude is conserved by the rotational dynamics alone, whereas the vector
being fixed in NED requires the attitude kinematics and the rotational dynamics
to agree with each other. A transposed direction-cosine matrix conserves the
magnitude and fails this.

RK4 is not symplectic, so this drift is secular rather than oscillatory — it
grows with integration length rather than staying bounded. Over the tens of
seconds a flight simulation runs it is far below every other error in the
model; over an orbit it would not be, and this is the wrong integrator for that.

**Torque-free precession.** For a body symmetric about its z-axis the
transverse angular-velocity vector rotates in the body frame at
`lambda = (Ia - It) n / It` with constant magnitude. Both an oblate case
(`lambda > 0`) and a prolate case (`lambda < 0`, where the precession runs the
other way round the body) are checked, and the check is that the error falls
like `h^4` as the step halves — not merely that it is small at one step. A
solution converging to the *wrong* closed form would sit at a small constant
error and pass an absolute check while failing this one outright.

**Intermediate-axis instability.** Rotation about the intermediate principal
axis is unstable with growth rate
`sigma = W sqrt((I3 - I2)(I2 - I1) / (I1 I3))`. Starting from a perturbation in
`e1` with `e3 = 0` gives `e1(t) = a cosh(sigma t)` and
`e3(t) = a sigma I1 sinh(sigma t) / ((I2 - I3) W)` — a cosh, not an exponential.
Both are asserted pointwise to a relative tolerance of 1e-4 over four
e-foldings. Rotation about the major and minor axes is checked to remain
bounded.

**Mass-property guard rails.** `MassProperties::validate()` rejects a
non-positive mass, an asymmetric inertia tensor, an indefinite one, and one
whose principal moments violate the triangle inequality `Ia + Ib >= Ic`. The
last of these is the one that catches a moment quoted about the wrong axis,
which passes every other check.

)";
  }

  std::cout << substitute(R"(## Aircraft modal characteristics

**Reference.** R. K. Heffley and W. F. Jewell, *Aircraft Handling Qualities
Data*, NASA CR-2144, Systems Technology Inc., December 1972.
NTRS 19730003312, <https://ntrs.nasa.gov/citations/19730003312>. The report's
own documentation page prints "Distribution Statement: Unclassified -
Unlimited", with no copyright notice and no limited-rights legend.

Aircraft NT-33A at flight condition 1 — sea level, M = 0.204, power approach.
The derivatives, the flight condition and the published modal results are
transcribed in `tests/validation/reference/nt33a_fc1.csv`; the state matrices
are assembled from the report's own equations (Appendix C pages C-1 and C-3),
because that is the only way to compare against the report's own answers.

**What is being validated.** The eigenvalue decomposition, the modal metrics,
the participation factors and the classification. Not a trim-and-linearise
chain — neither capability exists yet.

**How the tolerance is set.** Both sides of the comparison are rounded: the
report prints its derivatives to three significant figures and its modal
results to three. So the test perturbs each input by half a unit in its own
last printed digit, accumulates the resulting spread in each modal quantity,
and adds the published value's own rounding. The gate is that the disagreement
falls inside that band. The tolerance is therefore a property of the source
document rather than of the author's patience.

One subtlety that is easy to get wrong and does change the answer: the step
must be taken on the value AS PRINTED and then carried through whatever unit
conversion the value went through. `M_u*` is printed per second-foot; taking
half a unit in the last digit of its per-second-metre form understates its
uncertainty by the conversion factor of 3.28.

**Result.** Six of the seven published modal quantities reproduce within that
band: the spiral root, the roll-subsidence root, the Dutch-roll frequency and
damping, the phugoid frequency, and the short-period frequency and damping. All
five modes are also labelled correctly by participation factor alone, with
scores between {chain.min_label_score} and {chain.max_label_score}. The Dutch-roll period,
published separately in
Table II-10, agrees to within 1%.

### The phugoid damping ratio: localised, and no longer open

**Status changed.** This was recorded as an unexplained discrepancy. It is now
localised to the hand-assembled state matrix, and it does not appear in the
full chain.

Two independent routes to the same published number:

| Route | Phugoid zeta | vs published |
|---|---|---|
| State matrix assembled by hand from the report's Table II-3 dimensional derivatives | {hand.phugoid_zeta} | {hand.phugoid_percent} |
| Nonlinear model, trimmed, then linearised by central differences | {chain.phugoid_zeta} | {chain.phugoid_percent} |

The second route takes the report's NON-dimensional derivatives, builds a
nonlinear aircraft, finds its trim, and perturbs it. It shares no arithmetic
with the first beyond the source data, and it reproduces the published value.

So the discrepancy is in the hand assembly, not in the eigen-analysis and not
in the published value. What has NOT been established is which term the hand
assembly omits. The strongest remaining candidate is unchanged: the report
leaves `X_udot`, `X_wdot`, `X_q`, `Z_udot` and `M_udot` blank for this aircraft
and the hand assembly reads those blanks as zeros, while the nonlinear model
never needs them because it differentiates the forces directly.

The regression lock on the hand-assembled route stays, and is now anchored to
the trim-and-linearise result rather than to a bare measurement.

### Detail of the hand-assembled discrepancy

The phugoid damping ratio does **not** reproduce within the source's precision.
It disagrees by about 2% relative, which is roughly three times the band the
inputs' own rounding allows.

The mode itself is in very nearly the right place. Published, the phugoid
eigenvalue is {published.phugoid_real} ± {published.phugoid_imag}j; the hand
assembly gives {hand.phugoid_real} ± {hand.phugoid_imag}j. The imaginary parts
agree to a few parts in ten thousand. The disagreement is concentrated in a
derived quantity: ζ = |Re| / |λ| divides a small real part by a small natural
frequency, so a residual of a few times 1e-4 in the real part becomes
{hand.phugoid_percent} in the ratio — the entire discrepancy, accounted for but
not explained.

Two candidate explanations, neither confirmed:

1. **Terms read as zero that may mean "not supplied".** `X_udot`, `X_wdot`,
   `X_q`, `Z_udot` and `M_udot` are blank in the report's table for this
   aircraft and are taken as zero. `X_q` enters the phugoid directly through
   the `(−X_q + W_o)s` term of Appendix C's first row.
2. **Untranscribed coefficients.** The report's own longitudinal quartic is
   written in terms of `M_alpha` and `M_alpha_dot`, and its `D` and `E`
   coefficients were not transcribed. The phugoid roots are set by the
   low-order coefficients, so an omitted term would show there first.

Until this is resolved the phugoid damping ratio is listed as an open
discrepancy rather than as validated, and a **regression lock** — labelled as
one, per charter rule 8 — holds the gap at its measured size so it cannot grow
unnoticed, and fails if it shrinks, since that would mean the cause has been
found and the lock should become a validation.

)",
                          measured);

  std::cout << substitute(R"(## Frequency response and stability margins

**References.** G. F. Franklin, J. D. Powell and A. Emami-Naeini, *Feedback
Control of Dynamic Systems*, and K. J. Astrom and R. M. Murray, *Feedback
Systems*, for the classical margins. A. J. Laub, "Efficient multivariable
frequency response computations", IEEE TAC 26(2), 1981, for the Hessenberg
method. P. Seiler, A. Packard and P. Gahinet, "An Introduction to Disk Margins",
IEEE Control Systems Magazine 40(5), pp. 78-95, 2020,
doi:10.1109/MCS.2020.3005277, for the disk margin — consulted as the authors'
preprint <https://arxiv.org/abs/2003.04771>, since the published version is
paywalled.

### What is compared against what

Frequency response is gated against **arithmetic, not a document**. For a system
whose transfer function can be written down, G(jw) is a ratio of polynomials
evaluated at s = jw, and the state-space result must equal it to rounding. That
is a stronger reference than any printed table, because it has no precision of
its own to hide behind.

The same is true of two of the margin cases. The loop `1/(s(s+1)(s+2))` has a
phase crossover at exactly sqrt(2) rad/s — the phase reaches -180 degrees when
`1 - w^2/2` vanishes — and a gain margin of exactly 6, since
`|L(j sqrt2)| = 1/(sqrt2 sqrt3 sqrt6) = 1/6`. The loop `1/(s(s+1)^2)` crosses at
exactly 1 rad/s with a gain margin of exactly 2. Their gain crossovers are the
roots of stated cubics, solved in the test by an independent bisection.

The **delay margin** is checked twice over, and the second check is the one that
matters: applying exactly the reported delay must put the loop exactly on the
critical point, `1 + L(jw) e^(-jw tau) = 0`. A delay margin computed by the
wrong formula can still satisfy the formula it was computed from; it cannot
satisfy this.

### The disk margin

Gated against the tutorial's worked example, the loop
`L(s) = 25 / (s^3 + 10 s^2 + 10 s + 10)`.

| Quantity | galata | published | note |
|---|---|---|---|
| Classical gain margin | {disk.classical_gm} | 3.6 | Also exactly 90/25, since Im L = 0 at w = sqrt(10) |
| Classical phase margin | {disk.classical_pm} deg | 29.1 deg | |
| Peak of \|S - 1/2\| | {disk.peak} | 2.18 | |
| Disk margin alpha (skew 0) | {disk.alpha} | 0.46 | |
| Guaranteed gain range | {disk.gamma_min} to {disk.gamma_max} | 0.63 to 1.59 | |
| Guaranteed phase range | +/- {disk.phi_m} deg | — | Not printed by the paper; see below |
| Critical frequency | {disk.omega0} rad/s | 1.94 rad/s | **Discrepancy — see below** |

Every allowance is measured rather than chosen, in
`tests/validation/reference/seiler2020_disk_margin.csv`, which also records the
exact location of each value in the source and the rights position. ADR-0007
sets out why scalar results from a copyrighted paper may be committed at all
and what the limits on that are.

**The strongest evidence here is not a number.** The theorem's proof constructs
a perturbation on the boundary of the disk that destabilises the loop, placing a
closed-loop pole on the imaginary axis at the critical frequency. galata
computes that perturbation and the test closes the loop with it: the pole has to
land where the theorem says. That check fails for any transcription error in
alpha, delta_0 or f_0, individually or together, in a way that comparing
printed digits does not.

**A gap that had to be closed deliberately.** At skew 0 the factors
`(1 - sigma)` and `(1 + sigma)` are both 1, so the published example says
nothing about which is which. Swapping them in `gamma_min` was verified to leave
every skew-0 result identical. The intercepts are therefore additionally gated
against the disk parameterisation itself at six skews, and against the paper's
published closed forms for the two named one-sided margins.

**The guaranteed phase variation** is the one output with no peer-reviewed
reference: the paper derives the formula for phi_m but prints no number for this
example. It is gated against MathWorks' published `diskmargin` output for the
same loop, which is vendor documentation and is labelled as such in the table
above and in the reference file.

### A discrepancy in the source

The paper prints a critical frequency of 1.94 rad/s. Its own printed
`delta_0 = 0.212 - 0.406j` and `f_0 = 1.128 - 0.483j` are evaluated at that
frequency, and neither is reproduced there: at 1.94 the construction gives
`Re delta_0 = {disk.delta_real_at_printed}`, out by {disk.omega0_units_off} units
in the last figure the paper prints. Both are reproduced near {disk.omega0}
rad/s, which is where `|S - 1/2|` actually peaks, and which is the value galata
reports.

The printed critical frequency is therefore inconsistent with the rest of the
example. Because `|S - 1/2|` is flat near its maximum — a peak's location is
always more weakly determined than its height — this costs almost nothing in
the margin itself, which is why the published alpha, gamma_min and gamma_max all
agree. A test asserts the inconsistency directly, so that if a future reading of
the paper resolves it, the test fails rather than passing quietly.

### What these margins do not establish

Gain and phase margins are **separately-varied** margins: the tolerable gain
change with no phase change, and the reverse. A loop can show a comfortable
figure for each and still be fragile to a small simultaneous change in both.
That is the whole reason the disk margin is computed alongside them, and
`examples/nt33a-bank-loop-margins` is built to show it on a real aircraft — a
loop whose gain margin is infinite and whose disk margin is not.

Applied one loop at a time to a multi-loop system, all four are optimistic.
galata has no structured singular value, so it has no MIMO disk margin.

The disk margin's peak is found by **searching a frequency grid** and refining,
not by the exact Hamiltonian-eigenvalue method. A grid maximum is a lower bound
on the true peak, so the reported margin is an upper bound on the true one: the
error is in the optimistic direction. The grid is refined around the
closed-loop system's own lightly damped modes, which is where such peaks are,
and every result records the band and point count that were searched.

)",
                          measured);

  // Version only, deliberately NOT build_identification(): the report is
  // regenerated and diffed by CI on a different compiler and build type from a
  // developer's, and a footer naming the toolchain would make the diff fail for
  // a reason that has nothing to do with the numbers. The provenance of this
  // document is the commit it is committed in.
  std::cout << "---\n\nGenerated from galata " << galata::version_string()
            << " by `tools/validation/report_main.cpp`.\n";
  return 0;
}
