#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
#
# Renders the repository's Markdown into a small static site for GitHub Pages.
#
#   python3 scripts/build-docs-site.py [output-dir]      # default: build/site
#
# Design constraints, in the order that decided the design:
#
#   1. NOTHING IS HAND-MAINTAINED. The page list is discovered by scanning, so a
#      new ADR or a new document under docs/ appears on the site without anyone
#      remembering to add it. There is no navigation file to go stale.
#
#   2. THE SOURCES ARE NOT TOUCHED. docs/VERIFICATION.md is generated by
#      tools/validation/report_main.cpp and diffed by CI; adding Jekyll front
#      matter to it would make that diff fail forever. This script reads the
#      Markdown and writes HTML elsewhere, so the committed files stay exactly
#      as the generator produced them.
#
#   3. A LINK THAT LEAVES THE SITE STILL WORKS. Relative links that point at a
#      page on the site are rewritten to that page. Relative links that point at
#      anything else — a test, a CMake file, a reference CSV — are rewritten to
#      the file on GitHub, at the commit the site was built from. The result is
#      that "the reference values live in tests/validation/reference/..." is a
#      link a reader can actually follow.
#
# This is a documentation site, not a marketing site. It has no tracking, no
# fonts fetched from anywhere, no JavaScript, and no content that is not already
# in the repository.

import html
import os
import pathlib
import re
import sys

import markdown

ROOT = pathlib.Path(__file__).resolve().parent.parent
REPO = "celikgo/galata"

# The commit the links point at, so a link from the site is a link to the
# source the site was built from rather than to a moving branch.
REF = os.environ.get("GITHUB_SHA") or "main"
BLOB = f"https://github.com/{REPO}/blob/{REF}/"

TITLES = {
    "README.md": "galata",
    "CONTRIBUTING.md": "Contributing",
    "SECURITY.md": "Security policy",
    "CODE_OF_CONDUCT.md": "Code of conduct",
    "docs/CHARTER.md": "Charter",
    "docs/VERIFICATION.md": "Verification and validation",
    "docs/TESTING.md": "Testing",
    "docs/ROADMAP.md": "Roadmap",
    "docs/adr/README.md": "Architecture decision records",
    "docs/notes/phugoid-damping.md": "The phugoid-damping discrepancy",
}

# Order of the top navigation. Anything discovered but not named here is still
# built and still reachable; it just does not get a nav slot.
NAV = [
    ("README.md", "Overview"),
    ("docs/VERIFICATION.md", "V&amp;V report"),
    ("docs/CHARTER.md", "Charter"),
    ("docs/adr/README.md", "ADRs"),
    ("docs/ROADMAP.md", "Roadmap"),
    ("docs/TESTING.md", "Testing"),
    ("CONTRIBUTING.md", "Contributing"),
]


def discover():
    """Every Markdown file that becomes a page, mapped to its output path."""
    pages = {}
    for name in ("README.md", "CONTRIBUTING.md", "SECURITY.md", "CODE_OF_CONDUCT.md"):
        if (ROOT / name).exists():
            out = "index.html" if name == "README.md" else name[:-3].lower().replace("_", "-") + ".html"
            pages[name] = out
    for p in sorted((ROOT / "docs").glob("*.md")):
        pages[f"docs/{p.name}"] = p.stem.lower() + ".html"
    # Every subdirectory of docs/, not a list of the ones that exist today.
    # docs/notes/ was added after docs/adr/ and had to appear without this
    # function being edited, which is constraint 1 at the top of the file.
    for sub in sorted(d for d in (ROOT / "docs").iterdir() if d.is_dir()):
        for p in sorted(sub.glob("*.md")):
            out = (f"{sub.name}/index.html" if p.name == "README.md"
                   else f"{sub.name}/{p.stem}.html")
            pages[f"docs/{sub.name}/{p.name}"] = out
    return pages


def title_of(src, text):
    if src in TITLES:
        return TITLES[src]
    m = re.search(r"^#\s+(.+)$", text, re.M)
    return m.group(1).strip() if m else pathlib.Path(src).stem


def rewrite_links(md_text, src, pages):
    """Point relative Markdown links at the built page, or at GitHub."""
    src_dir = pathlib.PurePosixPath(src).parent
    out_dir = pathlib.PurePosixPath(pages[src]).parent

    def sub(m):
        label, target = m.group(1), m.group(2).strip()
        if re.match(r"^(https?:|mailto:|#)", target):
            return m.group(0)
        path, _, anchor = target.partition("#")
        anchor = f"#{anchor}" if anchor else ""
        if not path:
            return m.group(0)
        # Resolve the link against the directory of the file that contains it.
        # str.lstrip("./") must not be used here: it strips leading dots as a
        # character set and would turn ".github/workflows/ci.yml" into
        # "github/workflows/ci.yml", which resolves to nothing.
        resolved = os.path.normpath(str(src_dir / path)).replace(os.sep, "/")
        if resolved.startswith("./"):
            resolved = resolved[2:]
        # docs/assets/ is copied to the site root as assets/, so a link or an
        # image pointing into it must resolve to that copy. Sending it to a
        # GitHub blob URL instead would render an HTML page where the README
        # asked for a picture.
        if resolved.startswith("docs/assets/") and (ROOT / resolved).exists():
            rel = os.path.relpath("assets/" + resolved[len("docs/assets/"):],
                                  str(out_dir)).replace(os.sep, "/")
            return f"[{label}]({rel}{anchor})"
        if resolved in pages:
            rel = os.path.relpath(pages[resolved], str(out_dir)).replace(os.sep, "/")
            return f"[{label}]({rel}{anchor})"
        if (ROOT / resolved).exists():
            suffix = "/" if (ROOT / resolved).is_dir() else ""
            return f"[{label}]({BLOB}{resolved}{suffix}{anchor})"
        return m.group(0)

    # The label may itself contain a bracketed span — a badge is an image
    # nested inside a link, [![alt](img)](target). Allowing one level of
    # nesting makes the OUTER link the match, which is the one carrying the
    # relative target that needs rewriting.
    return re.sub(r"\[((?:[^\[\]]|\[[^\[\]]*\])*)\]\(([^)\s]+)\)", sub, md_text)


CSS = """
:root{--bg:#0B1016;--panel:#0E141C;--line:#1E2A38;--fg:#E6EDF3;--dim:#93A1AF;
--mute:#6B7885;--accent:#5BC8F5;--accent2:#FFB454;--code:#111922}
*{box-sizing:border-box}
html{-webkit-text-size-adjust:100%}
body{margin:0;background:var(--bg);color:var(--fg);
font:16px/1.65 -apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif}
header{border-bottom:1px solid var(--line);background:var(--panel);position:sticky;top:0;z-index:5}
.bar{max-width:1080px;margin:0 auto;padding:14px 24px;display:flex;flex-wrap:wrap;
gap:8px 22px;align-items:baseline}
.brand{font-size:21px;font-weight:600;color:var(--fg);text-decoration:none;letter-spacing:-.3px}
.brand span{color:var(--accent)}
nav{display:flex;flex-wrap:wrap;gap:8px 18px}
nav a{color:var(--dim);text-decoration:none;font-size:14.5px}
nav a:hover,nav a.on{color:var(--fg)}
nav a.on{box-shadow:inset 0 -2px 0 var(--accent)}
.gh{margin-left:auto;color:var(--mute);font-size:14px;text-decoration:none}
.gh:hover{color:var(--fg)}
main{max-width:1080px;margin:0 auto;padding:40px 24px 96px}
h1,h2,h3,h4{line-height:1.25;font-weight:600;margin:1.9em 0 .6em}
h1{font-size:34px;margin-top:.2em;letter-spacing:-.5px}
h2{font-size:25px;padding-bottom:.3em;border-bottom:1px solid var(--line)}
h3{font-size:19px}h4{font-size:16.5px;color:var(--dim)}
p,li{color:#CFD9E3}
a{color:var(--accent);text-decoration:none}
a:hover{text-decoration:underline}
strong{color:var(--fg)}
code{background:var(--code);border:1px solid var(--line);border-radius:4px;
padding:.12em .38em;font-size:.87em;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}
pre{background:var(--code);border:1px solid var(--line);border-radius:7px;
padding:15px 17px;overflow-x:auto}
pre code{background:none;border:0;padding:0;font-size:13.5px;line-height:1.6}
blockquote{margin:1.2em 0;padding:.1em 1.1em;border-left:3px solid var(--accent2);color:var(--dim)}
.tw{overflow-x:auto;margin:1.3em 0}
table{border-collapse:collapse;width:100%;font-size:14.5px}
th,td{border:1px solid var(--line);padding:8px 12px;text-align:left;vertical-align:top}
th{background:#131C26;color:var(--fg);font-weight:600;white-space:nowrap}
tr:nth-child(even) td{background:#0D141C}
img{max-width:100%;height:auto;border-radius:7px}
hr{border:0;border-top:1px solid var(--line);margin:2.4em 0}
footer{border-top:1px solid var(--line);color:var(--mute);font-size:13.5px;
max-width:1080px;margin:0 auto;padding:22px 24px 60px}
footer a{color:var(--mute);text-decoration:underline}
.note{background:var(--panel);border:1px solid var(--line);border-left:3px solid var(--accent2);
border-radius:0 7px 7px 0;padding:12px 16px;margin:0 0 28px;color:var(--dim);font-size:14.5px}
@media(max-width:640px){main{padding:26px 16px 70px}h1{font-size:27px}h2{font-size:21px}}
"""

# Substitution is done with str.replace, not str.format: the stylesheet is full
# of braces and every one of them would have to be doubled.
TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>@@TITLE@@</title>
<meta name="description" content="@@DESC@@">
<meta property="og:title" content="@@TITLE@@">
<meta property="og:description" content="@@DESC@@">
<meta property="og:image" content="https://celikgo.github.io/galata/assets/social-preview.png">
<meta name="twitter:card" content="summary_large_image">
<style>@@CSS@@</style>
</head>
<body>
<header><div class="bar">
<a class="brand" href="@@ROOT@@index.html">galata<span>.</span></a>
<nav>@@NAV@@</nav>
<a class="gh" href="https://github.com/@@REPO@@">GitHub &#8599;</a>
</div></header>
<main>
@@NOTE@@@@BODY@@
</main>
<footer>
Built from <a href="https://github.com/@@REPO@@/tree/@@REF@@">@@REF_SHORT@@</a>.
Apache-2.0. Nothing here is DO-178C qualified and it must never be used as
evidence in a certification package.
</footer>
</body>
</html>
"""

GENERATED_NOTE = (
    '<p class="note">This page is generated by the validation suite and checked '
    "by CI against what the code produces. It is not written by hand.</p>"
)


def main():
    out_root = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "build" / "site"
    pages = discover()
    if "README.md" not in pages:
        sys.exit("::error::README.md is missing — it is the site's index")

    ref_short = REF[:7] if len(REF) == 40 else REF
    built = 0

    for src, out in sorted(pages.items()):
        text = (ROOT / src).read_text(encoding="utf-8")
        title = title_of(src, text)
        # First non-empty paragraph, flattened, as the meta description.
        body_only = re.sub(r"^#\s+.+$", "", text, count=1, flags=re.M).strip()
        first = next((b for b in body_only.split("\n\n") if b.strip() and not b.startswith("<!--")), "")
        desc = html.escape(" ".join(first.split())[:180], quote=True)

        md = rewrite_links(text, src, pages)
        rendered = markdown.markdown(
            md,
            extensions=["tables", "fenced_code", "sane_lists", "attr_list", "toc", "md_in_html"],
            output_format="html5",
        )
        # Tables must scroll inside their own box rather than widening the page.
        rendered = rendered.replace("<table>", '<div class="tw"><table>').replace(
            "</table>", "</table></div>"
        )

        depth = len(pathlib.PurePosixPath(out).parts) - 1
        root_rel = "../" * depth
        nav = "".join(
            '<a class="%s" href="%s">%s</a>'
            % ("on" if nav_src == src else "", root_rel + pages[nav_src], label)
            for nav_src, label in NAV
            if nav_src in pages
        )

        dest = out_root / out
        dest.parent.mkdir(parents=True, exist_ok=True)
        page = TEMPLATE
        for token, value in (
            ("@@TITLE@@", html.escape(title, quote=True)),
            ("@@DESC@@", desc),
            ("@@CSS@@", CSS),
            ("@@NAV@@", nav),
            ("@@NOTE@@", GENERATED_NOTE if src == "docs/VERIFICATION.md" else ""),
            ("@@ROOT@@", root_rel),
            ("@@REPO@@", REPO),
            ("@@REF@@", REF),
            ("@@REF_SHORT@@", html.escape(ref_short)),
            ("@@BODY@@", rendered),
        ):
            page = page.replace(token, value)
        dest.write_text(page, encoding="utf-8")
        built += 1

    # Images referenced by the pages, and the social card.
    assets = ROOT / "docs" / "assets"
    if assets.is_dir():
        dest = out_root / "assets"
        dest.mkdir(parents=True, exist_ok=True)
        for f in assets.iterdir():
            if f.is_file():
                dest.joinpath(f.name).write_bytes(f.read_bytes())

    # GitHub Pages otherwise runs the output through Jekyll, which drops
    # directories beginning with an underscore and can rewrite what it finds.
    (out_root / ".nojekyll").write_text("")

    print(f"{built} page(s) -> {out_root}")
    for src, out in sorted(pages.items(), key=lambda kv: kv[1]):
        print(f"  {out:<34} <- {src}")


if __name__ == "__main__":
    main()
