// SPDX-License-Identifier: Apache-2.0
//
// Bench maps by least squares.
//
// THE SELF-TEST IS THE POINT. Every record below is SYNTHESISED from a known
// coefficient, so the question the tests ask is the only one worth asking of an
// estimator: given data generated by a value we chose, does it return that
// value, and does it say honestly how well it knows it?
//
// The noise is a fixed deterministic sequence rather than a random draw. A test
// that reseeds is a test that passes at some rates and not others, and ADR-0004
// wants the same bits every run.

#include "galata/data/record.hpp"
#include "galata/identify/static_fit.hpp"

#include <gtest/gtest.h>

#include <cmath>
#include <stdexcept>
#include <string>
#include <vector>

namespace {

using galata::data::Channel;
using galata::data::Record;
using galata::identify::fit_static;
using galata::identify::StaticFitRequest;
using galata::identify::Term;

// A deterministic, zero-mean, bounded wobble. Not a random number generator:
// the same sequence every run, on every platform.
double wobble(int index) {
  return std::sin(1.0 + 2.399963229728653 * static_cast<double>(index));
}

Record bench(double k_thrust, double noise_n, int samples = 24) {
  Record record;
  record.source_path = "synthetic";
  record.source_sha256 = std::string(64, '0');
  Channel speed{"rotor_speed_rad_s", "omega", "rad/s", "none", "", 1.0, 0.0, {}};
  Channel thrust{"thrust_n", "T", "N", "frd", "", 1.0, 0.0, {}};
  for (int i = 0; i < samples; ++i) {
    // Two decades of speed, which is what a bench sweep actually spans.
    const double w = 100.0 + 40.0 * static_cast<double>(i);
    record.times_s.push_back(0.1 * static_cast<double>(i));
    speed.samples.push_back(w);
    thrust.samples.push_back(k_thrust * w * w + noise_n * wobble(i));
  }
  record.channels = {speed, thrust};
  return record;
}

StaticFitRequest thrust_model() {
  StaticFitRequest request;
  request.response_channel = "thrust_n";
  request.terms = {{"rotor_speed_rad_s", 2.0, "k_thrust_n_s2", "N.s^2"}};
  return request;
}

}  // namespace

TEST(StaticFit, RecoversAKnownCoefficientFromNoisyData) {
  const double truth = 1.0e-5;
  // 0.05 N of scatter on thrusts of order 1 to 100 N.
  const auto fit = fit_static(bench(truth, 0.05), thrust_model());
  ASSERT_EQ(fit.coefficients.size(), 1u);
  const auto& k = fit.coefficients.front();
  EXPECT_EQ(k.name, "k_thrust_n_s2");
  EXPECT_EQ(k.unit, "N.s^2");
  EXPECT_NEAR(k.value, truth, 1e-8) << "the fit did not recover the coefficient it was given";

  // The truth must lie inside a few standard errors: an estimator whose value
  // is close but whose uncertainty claims otherwise is still wrong.
  ASSERT_TRUE(fit.uncertainty_is_estimable);
  EXPECT_GT(k.standard_error, 0.0);
  EXPECT_LT(std::fabs(k.value - truth), 3.0 * k.standard_error)
      << "the true value is outside three standard errors of the estimate";
  EXPECT_GT(fit.residual_rms, 0.0);
  EXPECT_EQ(fit.sample_count, 24);
  EXPECT_EQ(fit.parameter_count, 1);
}

// The case an estimator most often gets wrong by being confident. A perfect fit
// has demonstrated no scatter, so it supports no uncertainty at all — reporting
// zero would be claiming infinite precision from data that showed none.
TEST(StaticFit, NoiselessDataSupportsNoUncertaintyClaim) {
  const auto fit = fit_static(bench(1.0e-5, 0.0), thrust_model());
  EXPECT_NEAR(fit.coefficients.front().value, 1.0e-5, 1e-15);
  EXPECT_FALSE(fit.uncertainty_is_estimable) << "a noiseless fit must not report a standard error";
  EXPECT_DOUBLE_EQ(fit.coefficients.front().standard_error, 0.0);
  EXPECT_NE(fit.uncertainty_note.find("noiseless"), std::string::npos) << fit.uncertainty_note;
}

// As many parameters as samples: the fit passes through every point by
// construction and nothing is left over to estimate scatter from.
//
// Two samples and two parameters, not one and one — a single sample would be
// refused first, and correctly, because its regressor cannot vary.
TEST(StaticFit, AnExactlyDeterminedFitReportsNoUncertainty) {
  StaticFitRequest request = thrust_model();
  request.intercept = true;
  request.intercept_name = "offset_n";
  request.intercept_unit = "N";
  const auto fit = fit_static(bench(1.0e-5, 0.05, 2), request);
  EXPECT_EQ(fit.sample_count, 2);
  EXPECT_EQ(fit.parameter_count, 2);
  EXPECT_FALSE(fit.uncertainty_is_estimable)
      << "a fit through every point has nothing left over to estimate scatter from";
  EXPECT_NE(fit.uncertainty_note.find("exactly determined"), std::string::npos);
}

TEST(StaticFit, TheRangeItWasMeasuredOverIsReported) {
  const auto fit = fit_static(bench(1.0e-5, 0.05), thrust_model());
  ASSERT_EQ(fit.regressor_minimum.size(), 1u);
  EXPECT_DOUBLE_EQ(fit.regressor_minimum.front(), 100.0);
  EXPECT_DOUBLE_EQ(fit.regressor_maximum.front(), 100.0 + 40.0 * 23.0);
  // A coefficient is evidence about the range it was measured over and nothing
  // outside it; a reader extrapolating should have to ignore this to do so.
  EXPECT_GT(fit.response_maximum, fit.response_minimum);
}

TEST(StaticFit, DataThatCannotDetermineTheModelIsRefused) {
  // A regressor that never moves: the run did not excite what it measured.
  Record flat = bench(1.0e-5, 0.0, 6);
  for (double& sample : flat.channels[0].samples) {
    sample = 500.0;
  }
  EXPECT_THROW((void)fit_static(flat, thrust_model()), std::invalid_argument);

  // More parameters than samples.
  StaticFitRequest two_terms = thrust_model();
  two_terms.terms.push_back({"rotor_speed_rad_s", 1.0, "linear", "N.s"});
  two_terms.intercept = true;
  EXPECT_THROW((void)fit_static(bench(1.0e-5, 0.0, 2), two_terms), std::invalid_argument);

  // A channel the record does not carry.
  StaticFitRequest absent = thrust_model();
  absent.terms.front().channel = "no_such_channel";
  EXPECT_THROW((void)fit_static(bench(1.0e-5, 0.0), absent), std::invalid_argument);
}

// Terms that this data cannot tell apart. Over a narrow speed band, w and w^2
// are nearly proportional, and their coefficients trade against each other: the
// sum is determined and the parts are not. Refused rather than returned.
TEST(StaticFit, TermsThisDataCannotSeparateAreRefused) {
  Record narrow = bench(1.0e-5, 0.0, 40);
  for (int i = 0; i < 40; ++i) {
    // A band so narrow that w and w^2 are proportional to within round-off.
    const double w = 600.0 + 1e-7 * static_cast<double>(i);
    narrow.channels[0].samples[static_cast<std::size_t>(i)] = w;
    narrow.channels[1].samples[static_cast<std::size_t>(i)] = 1.0e-5 * w * w;
  }
  StaticFitRequest colinear = thrust_model();
  colinear.terms.push_back({"rotor_speed_rad_s", 1.0, "linear", "N.s"});
  EXPECT_THROW((void)fit_static(narrow, colinear), std::invalid_argument)
      << "coefficients that trade against each other must not be reported individually";
}

// The battery map is the same machinery: V = V_oc - I R is linear in its two
// parameters, so it is one term plus an intercept.
TEST(StaticFit, TheBatteryMapIsTheSameFit) {
  const double open_circuit = 25.2;
  const double resistance = 0.031;
  Record record;
  record.source_path = "synthetic";
  Channel current{"current_a", "I", "A", "none", "", 1.0, 0.0, {}};
  Channel voltage{"voltage_v", "V", "V", "none", "", 1.0, 0.0, {}};
  for (int i = 0; i < 16; ++i) {
    const double amps = 2.0 + 3.0 * static_cast<double>(i);
    record.times_s.push_back(static_cast<double>(i));
    current.samples.push_back(amps);
    voltage.samples.push_back(open_circuit - resistance * amps + 0.004 * wobble(i));
  }
  record.channels = {current, voltage};

  StaticFitRequest request;
  request.response_channel = "voltage_v";
  request.terms = {{"current_a", 1.0, "negative_resistance_ohm", "ohm"}};
  request.intercept = true;
  request.intercept_name = "open_circuit_voltage_v";
  request.intercept_unit = "V";

  const auto fit = fit_static(record, request);
  ASSERT_EQ(fit.coefficients.size(), 2u);
  EXPECT_NEAR(-fit.coefficients[0].value, resistance, 1e-3);
  EXPECT_NEAR(fit.coefficients[1].value, open_circuit, 1e-2);
  EXPECT_TRUE(fit.uncertainty_is_estimable);
}
